### ISSUE TITLE
How to zip a pdf or ppt file using jszip?

### ISSUE THREAD

**Issue by jetsonjohn** [Stuk/jszip#109]
I want zip a pdf or some other format like excel, ppt etc using jszip.

How to zip this format in jszip?

My code is as below

``` html
<BODY>
  <a id ='file' href="data/some.pdf" type="application/pdf; length=432628">Some.pdf</a>
  <input id="button" type="button" onclick="create_zip()" value="Create Zip"></input>
</BODY>
<SCRIPT>
        function create_zip() {
        var data = document.getElementById('file');
            var zip = new JSZip();
            zip.add(data, {base64: true});
            content = zip.generate();
            location.href = "data:application/zip;base64," + content;
        }
</SCRIPT>
```

What I want is that I will get the path of the file from the a element in the html. I want to zip the pdf using jszip

**Comment by tarikbenmerar** [comment]
@Mithgol as my pull request in github.com/jquery/jquery/pull/1525 has been dismissed due to the introduced code lines, please use this plugin https://github.com/acigna/jquery-ajax-native for arraybuffer support in jquery ajax.

**Comment by dhruvin16** [comment]
Can anyone please provide a solution for IE 10?
I looked out for Links. but not understood how to apply in code?

function create_zip() {
  var fileURL = $('#file').attr('href');
  var request = $.ajax({
    url: fileURL,
    type: "GET",
    contentType: "text/plain",
    mimeType:'text/plain; charset=x-user-defined' // <-[1]
  });     

  request.done(function( data ) {
    var zip = new JSZip();
    zip.file("my_file.pdf", data, { binary: true }); // <- [2]
    zip.generateAsync({ type: "blob" }).then(function (data) {
    saveAs(data, "example.zip");
    });
   
  });       
}

This Code download a Folder but When Open a File it is corrupted .
This issue is only for IE. Other browsers work perfectly.

**Comment by solidet** [comment]
Excuse me, I use pdfMake to create pdf. I can convert it to base64, but I fail to add file into zip. Could you help me with that?
