### ISSUE TITLE
Does anyone know when will jszip support password protected zip?

### ISSUE THREAD

**Issue by maordany** [Stuk/jszip#115]
Does anyone know when will jszip support password protected zip?

**Comment by Domvel** [comment]
@Stuk We could support encryption methods one by one. Throw an "not supported" error, if a encryption schema is not supported. And keep in mind, nothing is secure. This is not the topic. 
The password feature could be an experimental module which does not effect the rest of the zip algorithm and compression. A optional config. The developer should know that this is an experimental feature. It's better than nothing. 

First cryptoZip would be nice. AES awesome in the future.
https://github.com/Stuk/jszip/pull/129

I have also no idea about the encryption of zip. Not yet.
A use case to use a password could be: Prevent noobs from unzipping custom zip-container files. Many programs uses zip as container for their related files. e.g. libre office. (without encryption, just other file extension). It's not a security reason to encrypt a zip in this use case. Just make it harder for hacker.

I'm considering whether implementing a encryption feature to this zip library or developing a complete new library. But first I have to search the internet for zip or zip-like encryptions. There are implementations of AES in JavaScript and libraries. Maybe we can use this? But as I wrote, I have not yet an idea how to do this. 

@Stuk If you don't want a feature like this, I'll never create a pull-request. Just let me know please. :) Before I work for nothing. Are you considering to include an encryption feature to this library?
In best case as experimental uncritical optional configuration. This is not a promise for the implementation. Just considering. 🙂 

I didn't read all posts on the pull-request #129 I don't know what's wrong.

**Comment by xqdoo00o** [comment]
Hi, I add some Aes en/decryption code, please see at #656
