### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by jpillora** [Stuk/jszip#121]

**Comment by okv** [comment]
Hi there.

Any updates on this?
How is stream support going?

**Comment by Noitidart** [comment]
@okv if you want async, put jszip into a webworker. Its better then async. All operations are off the main thread, and the post message method is innately async.

**Comment by okv** [comment]
@Noitidart i'm using it on server side (node.js) and want to use default non-blocking approach for this environment - streams.

**Comment by dduponchel** [comment]
Here is the current state: #195 moved JSZip to async methods (and added stream support) and landed on the branch `jszip_v3`. #253 continues the work on the future v3 version and fixes most of #224.
Once #253 is merged, the only missing feature before a v3 release should be an improved support of Blob and Promise.

**Comment by okv** [comment]
@dduponchel got it, thanks for your detailed explanation

**Comment by dduponchel** [comment]
`v3.0.0` has been released.
