### ISSUE TITLE
Deprecate internal functions exposed in the public API

### ISSUE THREAD

**Issue by dduponchel** [Stuk/jszip#123]
Currently, JSZip exposes a lot of internal functions : 

```
JSZip.base64.decode
JSZip.base64.encode
JSZip.prototype.crc32
JSZip.prototype.utf8decode
JSZip.prototype.utf8encode

JSZip.utils.MAX_VALUE_16BITS
JSZip.utils.MAX_VALUE_32BITS
JSZip.utils.arrayBuffer2Blob
JSZip.utils.checkSupport
JSZip.utils.findCompression
JSZip.utils.getTypeOf
JSZip.utils.isRegExp
JSZip.utils.pretty
JSZip.utils.string2Blob
JSZip.utils.string2Uint8Array
JSZip.utils.string2binary
JSZip.utils.transformTo
JSZip.utils.uint8Array2String
```

These functions/objects are not documented and in my opinion not really useful outside JSZip. The base64/crc32/utf8 methods may have some uses for other people but their signatures are sometimes surprising (utf8encode takes a string and return a string for example).

I think we should deprecate the list above (keep them internally but flag their inclusion in the public API as deprecated).
Thoughts, anyone ?

**Comment by shytikov** [comment]
I have a question, why base64 should be abandoned?

So far as I can tell passing base64 string as an input for reading `zip`  is the only common method for in-memory file handling between node and browser.

Or there are another ways I'm missing?

Thank you so much in advance for your answer.

**Comment by dduponchel** [comment]
@shytikov this deprecates the object `JSZip.base64`, not the support of base64 input/output.
Regarding the node <-> browser communication, I would use `xhr.responseType = "arraybuffer"` (if you can [ignore IE <= 9](http://caniuse.com/#feat=xhr2))

**Comment by shytikov** [comment]
Thanks for the answer! 

But I don't see how I can output `base64` representation of file in archive...
