### ISSUE TITLE
Is there a way to resolve getBinaryContent for 2 files?

### ISSUE THREAD

**Issue by ghost** [Stuk/jszip#168]
Is there a way to resolve getBinaryContent for 2 files before generating a zip blob (via FileSaver) and handing it to the user? Also, in this process, is there a way to not nest 2 zip files, but instead have both requested files be directly inside the blob zip?

Thanks.

**Comment by chenster** [comment]
An example using counter suggested by @dduponchel  https://gist.github.com/noelvo/4502eea719f83270c8e9
