### ISSUE TITLE
Question: Progress Update

### ISSUE THREAD

**Issue by maol1** [Stuk/jszip#175]
Dear Developers

jszip does a big job on my webpage. The only feature I'm missing is a kind of a progress update. The creation of large files takes its time and it would be nice, if I could show a progress bar to the user. I already use jszip in a worker-process so the browser doesn't freeze. Would be nice, if I could pass an callback function as an option to the generate-function that get's called every few seconds.
Sorry for this request, but the code is way above my understanding for me to implement it myself...

Kind Regards
Oliver

**Comment by Kordonme** [comment]
I've successfully implemented code via a `setInterval()`, so it's indeed possible, but would be cool to have a callback.
My problem was the browser freezing, so I removed the code again. Didn't even think `Worker()`!

**Comment by Stuk** [comment]
This will be fixed by https://github.com/Stuk/jszip/pull/195

**Comment by dduponchel** [comment]
Implemented in `v3.0.0`, the [downloader example](https://stuk.github.io/jszip/documentation/examples/downloader.html) has been updated to include a progress bar: the [generateAsync()](https://stuk.github.io/jszip/documentation/api_jszip/generate_async.html) method has an update callback which get the percent of completion and the current file being processed.
