### ISSUE TITLE
Question: Progress bar whilst mini app downloader?

### ISSUE THREAD

**Issue by ghost** [Stuk/jszip#177]
Hey there,

Thank you for your work, is the backbone of what I have been recently working on here: http://ish0w.github.io/L0ck-for-plex-media-server/

Just a quick Q, is it possible to have a jQuery/js based progress bar for the % that is being downloaded in your example here: http://stuk.github.io/jszip/documentation/examples/downloader.html or in that I have been working on (link above[you'd need Plex Media Server to check it out though])

Thank you.

/iSh0w

**Comment by dduponchel** [comment]
Implemented in `v3.0.0`, the example has been updated to include a progress bar: the [generateAsync()](https://stuk.github.io/jszip/documentation/api_jszip/generate_async.html) method has an update callback which get the percent of completion and the current file being processed.
