### ISSUE TITLE
add non-text file to a new folder

### ISSUE THREAD

**Issue by pacmac** [Stuk/jszip#191]
This is more of a how-to question, I have searched the wiki but was not able to find a solution.

I need to be able to add a new folder to the zip file, and copy an image file to it.

```
zip.file("Hello.txt", "Hello World\n");
var img = zip.folder("images");
img.file("smile.gif", imgData, {base64: true});
```

In this example, is the smile.gif an existing file or is jszip creating the file ?

**Comment by demoblockchainapi** [comment]
imgData is not defined
What Does this error mean
This is my code
```
function create_zip() {
	var zip = new JSZip();

	// Add an top-level, arbitrary text file with contents
	zip.file("files/bing1.jpg", imgData, {base64: true});
	zip.file("files/bing2.jpg", imgData, {base64: true});
	zip.file("files/bing3.jpg", imgData, {base64: true});
	zip.file("files/bing4.jpg", imgData, {base64: true});

	// Generate the zip file asynchronously
	zip.generateAsync({type:"blob"})
	.then(function(content) {
	    // Force down of the Zip file
	    saveAs(content, "<?=$filename?>");
	});
}
```
And i included 
     <script type="text/javascript" src="jszip/dist/jszip.min.js"></script>
	<script type="text/javascript" src="jszip/vendor/FileSaver.js"></script>
