### ISSUE TITLE
Question: Downloading multiple remote images

### ISSUE THREAD

**Issue by WassifAziz** [Stuk/jszip#192]
I'm trying to download multiple images from a remote address (of which i have access to).

I've been following the code here
http://lifelongprogrammer.blogspot.co.uk/2014/06/using-jszip-to-download-multiple-remote-images.html

I can't seem to get it working. It does try to download something from the specified page but it seems to be trying to download random file names like:

h
a
d
d
c
:
a
t
o
p
a

Can someone give me some guidance on what i need to do. i was hoping i could get it to download all files from a specified folder

**Comment by Stuk** [comment]
The code at that link looks like it should work if you call `downloadAllImages` with an array of strings:

```js
downloadAllImages(['one.png', 'two.txt', ...]);
```

**Comment by WassifAziz** [comment]
I've managed to it working thanks, I didn't realise I had to define an
array with all the image paths.

Thanks for the help! :)
