### ISSUE TITLE
remove file in zip not valid

### ISSUE THREAD

**Issue by BiteBit** [Stuk/jszip#193]
coffee-script style

```
JSZip = require 'jszip'
fs = require 'fs'

file = './Mail.zip'
fs.readFile file, (err, data)->
  throw err if (err)
  zip = new JSZip(data)
  zip.remove 'Mail/manifest.json'
```

the manifest.json still in the zip archive when the the code finish
is there something wrong in my code ?

**Comment by dduponchel** [comment]
Your code should work, but it will do nothing if `Mail/manifest.json` is not in the zip file. Could you check what's inside `zip.files` ? The file names are used as keys, `Object.keys(zip.files)` will give you the list of the files.

**Comment by edi9999** [comment]
I think @BiteBit would expect that the file will be changed without specifying the save location.

you would need to do this:

```
JSZip = require 'jszip'
fs = require 'fs'
file = './Mail.zip'
fs.readFile file, (err, data)->
  throw err if (err)
  zip = new JSZip(data)
  zip.remove 'Mail/manifest.json'
  fs.writeFileSync("out.zip",zip.generate("nodebuffer"))

```

**Comment by BiteBit** [comment]
@edi9999 
oh, thank you very much, i try generate, but forget the option
it's my fault
