### ISSUE TITLE
[ERROR]TypeError: Buffer.isBuffer is not a function

### ISSUE THREAD

**Issue by anhhh11** [Stuk/jszip#196]
I run following code:
```
var docZipped = JSZip();
var docOutput = doc.output("arraybuffer");
docZipped.file(wbid + ".pdf", docOutput, { binary: true,createFolders:true,comment:wbid});
var content = docZipped.generate({ type: "base64", compression: "DEFLATE"});
saveAs(content, wbid + ".zip");
```
but got: TypeError: Buffer.isBuffer is not a function line 594 ( Test on both Firefox 34.0.5 and Google Chrome 39.0)
```
module.exports.test = function(b){
    return Buffer.isBuffer(b);
};
```
Then I try to change it to:
```
module.exports.test = function(b){
    return b instanceof Buffer;
};
```
But when downloading, though it show download dialog of 1234.zip but the file inside only has name 1234-1 without pdf extension; Is Buffer checking fail rising this kind of weird behavior?

**Comment by dduponchel** [comment]
The Buffer check should only be triggered when an implementation of nodejs Buffer is available. I think that you have a `Buffer` on your page and JSZip mistakes it for a nodejs one. Try forcing the nodejs support if you are in a browser (the check should be improved, but that may help you now) :

```js
JSZip.support.nodebuffer = false;
```
I tested this with your example (just changing `type: "base64"` to `type: "blob"`) but I get the right file name. Could you double-check the name you use and check `Object.keys(docZipped.files);` ?

**Comment by anhhh11** [comment]
After your assigning, and also change type to "blob", it work as expected, thanks.
```
JSZip.support.nodebuffer = false;
```
