### ISSUE TITLE
Bump version and update NPM package

### ISSUE THREAD

**Issue by RickyChien** [Stuk/jszip#204]
Hi @Stuk , I saw JSZip version is still in 2.4.0 bumped about 8 months ago. It would be very appreciated if someone can come out to update and publish new version.

Thanks!

**Comment by dduponchel** [comment]
After #205, a v2.5.0 sounds good.

**Comment by Stuk** [comment]
@dduponchel merged! Ready for a release?

**Comment by Stuk** [comment]
Seems like saucelabs is [having problems right now](http://status.saucelabs.com/), so our tests aren't passing. Hopefully it will be fixed soon.

**Comment by dduponchel** [comment]
Saucelabs is back and the tests now pass. I'll prepare the pull request for the release.

**Comment by Stuk** [comment]
2.5.0 is out

**Comment by RickyChien** [comment]
Wow thanks!!

**Comment by RickyChien** [comment]
@Stuk I saw NPM was updated but github releases is still in 2.4.0.

**Comment by Stuk** [comment]
Ah, needed to create a git tag as well. This is now done
