### ISSUE TITLE
Do you support gzip decompression and compression?

### ISSUE THREAD

**Issue by wwwpol** [Stuk/jszip#209]
I am looking to compress my JSON before I send it to the server via a PUT call.  Does this library support gzip?

**Comment by Stuk** [comment]
No, it only supports the DEFLATE compression used in the zip format

**Comment by wwwpol** [comment]
I don't know if you have future plans for adding this option, but I would +1 on that feature.

**Comment by Stuk** [comment]
Afraid not: https://github.com/Stuk/jszip/issues/189
