### ISSUE TITLE
Wrong names

### ISSUE THREAD

**Issue by iNovozhilov** [Stuk/jszip#210]
Новая папка.zip
```
> Новая папка/
> Новая папка/Новый текстовый документ.txt
```
result:
```bath
> file = fs.readFileSync('D:\\Новая папка.zip')
<Buffer 50 4b 03 04 14 00 00 00 00 00 a1 5a 87 46 00 00 00 00 00 00 00 00 00 00 00 00 0c 00 00 00 8d ae a2 a0 ef 20 af a0 af aa a0 2f 50 4b 03 04 0a 00 00 00 00 ...>
> zip.load(file)
{ files:
   { '®¢ ï ¯ ¯ª /':
      { name: '®¢ ï ¯ ¯ª /',
        _data: null,
        options: [Object] },
     '®¢ ï ¯ ¯ª /®¢ë© â¥ªáâ®¢ë© ¤®ªã¬¥­â.txt':
      { name: '®¢ ï ¯ ¯ª /®¢ë© â¥ªáâ®¢ë© ¤®ªã¬¥­â.txt',
        _data: [Object],
        options: [Object] } },
  root: '',
  clone: [Function] }
```

**Comment by dduponchel** [comment]
If I remember correctly, Windows uses the locale of the machine for the file name encoding (I suspect [Windows-1251](http://en.wikipedia.org/wiki/Windows-1251) here). We currently use utf-8 to decode the file name (and the content with `asText()`).

- how did you create the zip file ? The default compressed folders feature on windows ?
- could you upload somewhere (or send it by email) this zip file ?

We can't include each and every encoding in JSZip ([iconv-lite](https://github.com/ashtuchkin/iconv-lite) is ~180k minified and compressed for example) but we could provide an external hook to decode the file name.

**Comment by IDrakon** [comment]
The archive created: [7-zip](http://www.7-zip.org/)
File names in windows for the Russian version encoded in cp866, it is supported by iconv: [Supported-Encodings](https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings)
File: [Новая папка.zip](https://drive.google.com/open?id=0B79v8XZ-aTqwZ3NYTTdTMTNyREU&authuser=0)

**Comment by dduponchel** [comment]
Could you check my branch [improve_encoding_support](https://github.com/dduponchel/jszip/tree/improve_encoding_support) ?

```js
var iconv = require('iconv-lite');
zip.load(file, {
  decodeFileName: function (bytes) {
    return iconv.decode(bytes, 'cp866');
  }
});
```

If everything is ok I will create a pull request.

**Comment by IDrakon** [comment]
it works:
```js
{ files:
   { 'Новая папка/':
      { name: 'Новая папка/',
        dir: true,
        date: Mon Apr 13 2015 19:31:12 GMT+0300 (RTZ 2 (зима)),
        comment: null,
        unixPermissions: null,
        dosPermissions: 16,
        _data: null,
        options: [Object],
        _initialMetadata: [Object] },
     'Новая папка/Новый текстовый документ.txt':
      { name: 'Новая папка/Новый текстовый документ.txt',
        dir: false,
        date: Mon Apr 13 2015 19:31:12 GMT+0300 (RTZ 2 (зима)),
        comment: null,
        unixPermissions: null,
        dosPermissions: 32,
        _data: [Object],
        options: [Object],
        _initialMetadata: [Object] } },
```
