### ISSUE TITLE
Too many conflicting docs on how to handle NodeJS and none work for images.

### ISSUE THREAD

**Issue by iDVB** [Stuk/jszip#212]
I read thru almost all the issues open and closed and found quite a few talking about manually unzipping files generated with JSZip resulting in *cpgz* files.  This is also what is happening in my case.

The JSZip docs say to do this...
`zip.generate({type:'nodebuffer'}));`

...some say to do this...
`zip.generate({type:'nodebuffer'}), 'binary');`

...others say to do this...
`zip.file(file, buffer, {date: stat.mtime, unixPermissions: stat.mode });`

...some say this...
`zip.generate({type:"nodebuffer", platform: process.platform}), 'binary');`

...none seem to work.

Here is my code...
```javascript
recursiveAsync(DIRECTORY_TO_ZIP)
.then(function(files){
	return Promise.join(files.map(function(file){
		return fs.readFileAsync(file).then(function(data){
			return fs.lstatAsync(file).then(function(stat){
				return Promise.resolve(zip.file(file, data));
			});
		});
	}));
})
.finally(function(){
	return fs.writeFileAsync(
		OUTPUT_DIRECTORY+'screenshots.zip', 
		zip.generate({type:"nodebuffer"}));
})
.catch(function(err){
	console.error(err);
});
```
A few quick notes, I'm using [Bluebird](https://github.com/petkaantonov/bluebird) for Promises and `recursiveAsync()` is a function that returns an array of filePaths recursively.

**Comment by iDVB** [comment]
...so I got something to work and now I'm baffled...
```javascript
var file = 'test/images/desktop/1.png';
fs.readFileAsync(file).then(function(data){
	return fs.lstatAsync(file).then(function(stat){
		return Promise.resolve(zip.file(file, data));
	});
})
.finally(function(){
	var data = zip.generate({type:'nodebuffer'});
	return fs.writeFileAsync(OUTPUT_DIRECTORY+'screenshots.zip', data);
})
.catch(function(err){
	console.error(err);
});
```

which is essentially the same code but only a single image being added rather then the previous which is trying to recursively add all of these...
```
test/images/desktop/1.png
test/images/desktop/2.png
test/images/desktop/3.png
test/images/desktop/4.png
test/images/mobile/ios-safari-screens.page.baseline.png
test/images/mobile/ios-safari-screens.page.regression.png
test/images/mobile/ios-safari-screens.png
```

why would adding only one work but not all of these? Did I mess up the promises somehow?

**Comment by dduponchel** [comment]
I found the issue : [Promise.join](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisejoinpromisethenablevalue-promises-function-handler---promise) takes a function as last argument but you don't have one. If I add `console.log` in your code, I get

```
write file
adding test/images/desktop/2.png
adding test/images/desktop/1.png
adding test/images/desktop/3.png
...
```
The zip is created empty, then the content is added (too late). If I replace [Promise.join](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisejoinpromisethenablevalue-promises-function-handler---promise) with [Promise.all](https://github.com/petkaantonov/bluebird/blob/master/API.md#all---promise), I get 
```
adding test/images/desktop/1.png
adding test/images/desktop/2.png
...
write file
```
And a complete zip. Does this solve your issue ?

**Comment by iDVB** [comment]
I have not tried it yet, but I'd bet I t does! Thanks.

I found another fix but I like your .all better.

My fix was to use Promise.reduce() to go over them in sequence. But I'd rather it with .all and all at once. :)
