### ISSUE TITLE
How to use JSZip on IIS server?

### ISSUE THREAD

**Issue by hedogn** [Stuk/jszip#214]
I want to generate a ZIP file on  IIS server(Windows 2003 Server), use ASP(not ASP.NET).
How to use JSZip?

**Comment by IanYates** [comment]
If you're using VBScript with your classic ASP (as most sites did), then JSZip is pretty much inaccessible to you.  Even if you were using JScript I suspect you'd still run into troubles.

The best thing would be to use some COM library that supports ZIP manipulation.  A quick search: http://www.bing.com/search?q=asp+vbscript+zip+file&src=IE-TopResult&FORM=IETR02&conversationid= 

Something there ought to help.

**Comment by Stuk** [comment]
Thanks @IanYates. I don't think there's much we can do.
