### ISSUE TITLE
Add travis button to the README

### ISSUE THREAD

**Issue by erikvold** [Stuk/jszip#218]
This would make it easier to see the status travis tests, and take a look at them imho.

**Comment by Mithgol** [comment]
There is a Travis CI button in README.

I've changed it to SVG in 915e2f8b5298bb5d701ec4093c0439853f16111a though. Does you browser not support SVG?

**Comment by dduponchel** [comment]
The button is already [here](https://github.com/Stuk/jszip#test-status).
