### ISSUE TITLE
Is it possible to set the charactere encoding for the files being added to the zip?

### ISSUE THREAD

**Issue by UlyssesAlves** [Stuk/jszip#220]
I am trying to zip multiple CSV files, but non-english characteres are being displayed wrongly when the CSVs are opened in Excel. I know the problem is because I am not defining ANSI as the char encoding for these CSV files, but I don't know how I can do this with jszip.

Currently I have this code, but when there are non-english characteres they appear mismatched to the end user viewing the file in Excel.

```javascript
zip.file(csvFileName, csvFileContents);
```

Is there a way for me to pass the file encoding when adding the file to the zip object, as shown in the code below?

```javascript
// Is there a way to do this?
zip.file(csvFileName, csvFileContents, "data:text/csv,charset=ANSI");
```

**Comment by dduponchel** [comment]
JSZip only supports UTF-8 for text content but you can encode the text with the encoding of your choice on your side and give the binary to JSZip:

```js
var iconv = require('iconv-lite');
var csvBinary = iconv.encode(csvFileContents, 'cp1252'); // assuming ANSI is cp1252

zip.file(csvFileName, csvBinary);
```

I use [iconv-lite](https://www.npmjs.com/package/iconv-lite) here but any encoding library will work (just add a `{binary:true}` if it outputs an other string).

You can decode the text that way:

```js
var u8 = zip.file(csvFileName).asUint8Array();
var csvFileContents = iconv.decode(u8, 'cp1252');
```

**Comment by UlyssesAlves** [comment]
This looks like it will work. The only problem is that "require" function. Where does it come from?

**Comment by dduponchel** [comment]
That's the nodejs' `require`. In a browser, you will need to convert ``iconv-lite` first with browserify. But any library will work: if you prefer [windows-1252](https://github.com/mathiasbynens/windows-1252) (which may be easier to use in a browser), you can:
```js
var csvBinary = windows1252.encode(csvFileContents);
zip.file(csvFileName, csvBinary, {binary:true});
```

**Comment by UlyssesAlves** [comment]
It worked! Thank you for your support.

**Comment by stavros-liaskos** [comment]
In my case, I am developing a user script in Greasemonkey that zips csv files with non-english characters.
So local build is not an option for me. Any ideas how I can solve this with "inline" javascript??
