### ISSUE TITLE
Zip a large file

### ISSUE THREAD

**Issue by token97** [Stuk/jszip#222]
Are there best practices to create an archive from a large folder?
I'm trying to zip a folder witch contains a lot of pictures (around 9Go) in NodeJs, but the script dies with error "out of memory".
full error : FATAL ERROR: node::smalloc::Alloc(v8::Handle<v8::Object>, size_t, v8::ExternalArrayType) Out Of Memory

**Comment by token97** [comment]
I finally switch on <a href='https://github.com/archiverjs/node-archiver'>node-archiver </a>

**Comment by SteffenLanger** [comment]
@token97, thank you for the hint! This is what I did, too. The performance is great and it does not show any memory issues.

**Comment by Julycc41** [comment]
> 我终于打开了[节点归档器](https://github.com/archiverjs/node-archiver)

How do I change it? Do I write it directly in Node
