### ISSUE TITLE
What to put in JSZip v3 ?

### ISSUE THREAD

**Issue by dduponchel** [Stuk/jszip#224]
If #195 is merged, the existing API will completely change and that will need a v3.0.0 release. We could use this release to add other (maybe) breaking changes.

I think of the following breaking changes:
- remove the defensive copy in JSZip#filter. Users already have access to `zip.files`, a defensive copy is pointless here.
- remove the deprecated API (see #123)
- add `base64` support in `async()`
- change the `createFolders` default value from `false` to `true`. People are used to file managers creating folders, the `false` value is (only ?) needed when we don't generate a regular zip file (xlsx file for example)
- restrict content using JSZip.root in JSZip.generate (see #203)
- remove `JSZip.compressions`, it now requires internal objects to work
- make the `type` option in `generateAsync()` mandatory

Other non-breaking changes that could be nice to have:
- a JSZip#forEach method
- Blob input support (the user won't need anymore a FileReader)
- Promise input support

Do you have other ideas ? remarks ?

**Comment by shytikov** [comment]
It would be nice if `asText()`could support different encodings.

**Comment by dduponchel** [comment]
@shytikov Given the number of different text encodings, I don't think it's a good idea to bundle them into JSZip. The easiest way to support an other encoding is to get an Uint8Array and call an other lib to decode the text. You're not the only one interested in this feature, a FAQ entry or an new [example](http://stuk.github.io/jszip/documentation/examples.html) would be great.

What's your use case for a `base64` file export ?

**Comment by shytikov** [comment]
@dduponchel about `base64`... since you're removing deprecated API, it's not possible to use `JSZip.base64` object to encode binary file to `base64` without extra work: sending to buffer, and receiving result from it. But this action is node specific. On browser you will need to use another approach to perform transformation.

And `JSZip` actually bundled with seamlessly working `base64` code... And it could not be used in case of exporting file... So another library should be used... Why if we can add 5 lines of code that will export extracted file not only `asText()`, but `asBase64()` as well.

**Comment by shytikov** [comment]
I guess support of BinaryStrings may be removed, since in `node.js` it's marked as deprecated...

**Comment by dduponchel** [comment]
I see your point. We can indeed add base64 as an output type (and that would be consistent with `generate`).
I tried to remove the deprecated API but I couldn't remove `JSZip.base64`: it is used in the unit tests. The current base64 encode/decode signatures are awkward (they work with base64 strings and binary strings) but we could update them instead of removing them.

**Comment by Stuk** [comment]
Thanks for all the great work David. Here are my thoughts:

All the breaking changes sound like good suggestions. This is the perfect time to remove any deprecated APIs.

I'm wondering what you mean by promise input support?

For deprecating `JSZip.base64`, we could move that code into the test directory, to only be used by the tests if necessary.

**Comment by dduponchel** [comment]
By "promise input support", I meant allowing a Promise of a String/Uint8Array/other in `file(name, data)` and `loadAsync()`. Browsers seem to use more and more promises (in the fetch API for example), it may be easier to just add the promise instead of first resolving it. Allowing a Blob means having async data, adding Promise support is almost free after that.
The only downside I see with async data is the error handling: the user will see the issue with a `Promise.resolve(new Date())` when generating a zip file or getting the file content. If we return a Promise, we break the chainability of the API (`file(name, data)` currently returns the updated JSZip instance).

It may be a little strange to put the base64 code in the test directory, we could also add a test helper to expose base64 functions only in the tests (we will need an other build to browserify the base64 code either way).
After a quick search on github, it seems that `JSZip.base64` is used a lot to emulate the missing "asBase64()" method but also because they sometimes need to base64 encode/decode and we provide the methods. Keeping/upgrading these methods could also make sense.

**Comment by dduponchel** [comment]
`v3.0.0` has been released.
