### ISSUE TITLE
zip nested folder

### ISSUE THREAD

**Issue by leizard** [Stuk/jszip#244]
Hi, thank you for awesome plugin. I want to zip a folder with nested child folders inside it. The problem is zip.folder doesn't have callback function. So if I do something like this

```
        var zip = new JSZip();
        createFolder(folderid, zip);

        function createFolder(folderId, zipParent) {
            var folder = Folders.findOne(folderId);
            var zipfolder = zipParent.folder(folder.name);
            if (folder.childFolders) {
                _.each(folder.childFolders, function(childFolder) {
                    createFolder(childFolder._id, zipfolder);
                })
            }
        }
```

I don't know when it complete creating folder, so the code behind could behave incorrectly.

Is there any good solution for this case ? Thank you.

**Comment by dduponchel** [comment]
The `zip.folder` method is synchronous: it only creates an entry (and possibly parent folders) and stores it to `zip.files`.
When it returns, everything is done. In your example, when the initial `createFolder` returns, `zip` contains the full tree.
