### ISSUE TITLE
Downloader example doesn't work correctly

### ISSUE THREAD

**Issue by valentinfltv** [Stuk/jszip#245]
Hello.
I want to realize zipping .exe files from server, while somebody downloads files using checkboxes, but not the point. Trying to understand how jszip works. But I have some issues : downloader example doesn't work correctly. I take an example , delete some excess features like styles, links etc. Almost all runs correct except block: 
Almost all runs correct except block: <br> **JSZipUtils.getBinaryContent(url, function (err, data) {..}**
<br>this section doesn't execute, it gives me an **error** : <br> " Error: InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is" or 'text'(was'arraybuffer'). " <br>
 Also I have another question: if I place script "demo.js" in header section script doesn't run by pressing button. Scripts should be downloaded because they are small size and header loading faster then body. I read that best way to include scripts is to place they right in the end of body, before closing tag. But if I place all my scripts in the end of body nothing happens when button is pressed. Why it works that way? I red many articles but don't find an answer. 
I'm new in JS so don't beat me hard). 
I'll be very appreciate for any help and suggestions

this is my 1.html file:

```
<!DOCTYPE html>
<html lang="en">
  <head>
<meta charset="utf-8">
<title>shit</title>
 <script type="text/javascript" src="dist/jszip.js"></script>
 <script type="text/javascript" src="dist/jszip-utils.js"></script>
 <script type="text/javascript" src="dist/jquery-1.8.3.min.js"></script>
 <script type="text/javascript" src="dist/FileSaver.js"></script>
  </head>
  <body>
<form action="#" id="download_form">
<ul>
    <li>
      <label>
       <input type="checkbox" data-url="dist/jszip.js" checked />
    dist/jszip.js
  </label>
</li>
<li>
  <label>
    <input type="checkbox" data-url="dist/demo.js" checked />
    dist/demo.js
  </label>
</li>
<li>
  <label>
    <input type="checkbox" data-url="dist/FileSaver.js" />
    dist/FileSaver.js
  </label>
   </li>
  </ul>
 <button type="submit" class="btn btn-primary">pack them !</button>
</form>
<script type="text/javascript" src="dist/demo.js"></script>
  </body>
 </html>
```

and here is demo.js:

```
  jQuery(function ($) {
  "use strict";

function deferredAddZip(url, filename, zip) {
    var deferred = $.Deferred();
    JSZipUtils.getBinaryContent(url, function (err, data) {
        if(err) {
            deferred.reject(err);
        } else {
            zip.file(filename, data, {binary:true});
            deferred.resolve(data);
        }
    });
    return deferred;
}

 var $form = $("#download_form").on("submit", function () {

    var zip = new JSZip();
    var deferreds = [];

    // find every checked item
    $(this).find(":checked").each(function () { 
        var $this = $(this);
        var url = $this.data("url");
        var filename = url.replace(/.*\//g, "");
        deferreds.push(deferredAddZip(url, filename, zip));
    });

    // when everything has been downloaded, we can trigger the dl

    // section below doesn't work at all - alerts used for simplest debugging

    $.when.apply($, deferreds).done(function () {

        var blob = zip.generate({type:"blob"});

        // see FileSaver.js
        saveAs(blob, "example.zip");

    }).fail(function (err) {
        alert(err);
    });
    return false;
  });
});
```

my file folder which includes files looks like:
-root folder:
- 1.html
  - subfolder "dist":
    - demo.js
    - FileSaver.js
    - jquery-1.8.3.min.js
    - jszip.js
    - jszip-utils.js

**Comment by dduponchel** [comment]
Regarding the first issue:
I don't reproduce the issue and the source code looks good, `JSZipUtils._getBinaryFromXHR` first tries `xhr.response` (which should be defined in your case) before `xhr.responseText`.

Which browser do you use and what file is being downloaded ? Does the [original example](http://stuk.github.io/jszip/documentation/examples/downloader.html) works for you ?

For the second issue:
I tested with all scripts in the `<head>` and all scripts at the end of the body, both use cases worked fine. You should see any error in the js console of your browser if something doesn't work.

If you don't see any error, you should check that you don't bind the click event too early. The first line `jQuery(function ($) {` [will wait](http://api.jquery.com/jQuery/#jQuery3) for the DOM to be ready before executing the callback. Without this line and with a `<script>` in the `<head>`, the DOM won't be ready and `$("#download_form").on("submit", ...` will do nothing.

**Comment by valentinfltv** [comment]
I use Google Chrome, nothing being downloaded. Original example is working normally.
In chrome javascript console I've got next error: 
 - XMLHttpRequest cannot load file:///C:/Users/LuckyMan/Desktop/New%20folder/dist/jszip.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
Looks like problem is that I used 'file' protocol. Trying to run this example on https://jsfiddle.net/ but it shows message that I should use POST-method.
Is there some way to run my example on my local machine?
Thank you so much for your answer.

**Comment by dduponchel** [comment]
I reproduced the issue with chrome and a `file:///` url.
`file:///` urls are difficult to use because browsers usually restrict them for security reasons (see [my comment here](https://github.com/Stuk/jszip-utils/pull/3#issuecomment-43402605)).
You will avoid *a lot* of issues if you use a local http server (with this issue but also with web development in general). Any web server will work, I think [apache httpd](http://httpd.apache.org/docs/current/platform/windows.html) or [nginx](http://nginx.org/en/docs/windows.html) is a good starting point.

**Comment by valentinfltv** [comment]
Thank you so much.
I install Apache server, use it for starting my html example and it works perfect.
Thanks a lot, You helped me resolve my problem.

**Comment by Mithgol** [comment]
This issue should be closed.
