### ISSUE TITLE
unable to know if file is a symlink

### ISSUE THREAD

**Issue by GuyMograbi** [Stuk/jszip#257]
when I unzip, I don't have a way to know if the file is a symlink or not. 
i am trying to implement a way to preserve symlinks.

**Comment by dduponchel** [comment]
If the file has been generated with UNIX permissions (and without following the symlinks), you can find this information in `unixPermissions`. You can check how [the linux kernel does](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/stat.h#n19):

```c
#define S_IFMT  00170000
// ...
#define S_IFLNK	 0120000
// ...
#define S_ISLNK(m)	(((m) & S_IFMT) == S_IFLNK)
```

First, let's create a test file:
```bash
# in a shell
echo "aa" > file
ln -s file link
zip --symlinks archive.zip file link
```

Then, we read it with JSZip:
```js
// I use nodejs here because it's easier to read a local file
// but you can use a browser if you prefer
var JSZip = require("JSZip");
var fs = require("fs");
var content = fs.readFileSync("archive.zip");

var zip = new JSZip(content);
(zip.file("file").unixPermissions & 0170000) === 0120000; // false, this is a regular file
(zip.file("link").unixPermissions & 0170000) === 0120000; // true, this is a symlink
zip.file("file").asText(); // 'aa\n'
zip.file("link").asText(); // 'file'
```

Does this solve your issue ?

**Comment by dduponchel** [comment]
Without update, I'll close this issue. Feel free to comment or open a new one if you still have troubles.
