### ISSUE TITLE
SCRIPT5022: Corrupted zip : can't find end of central directory 

### ISSUE THREAD

**Issue by showlovel** [Stuk/jszip#26]
waht  cause this problem ? path? ol

**Comment by nathfreder** [comment]
I'm still having this issue.

**Comment by dk511** [comment]
I got this issue today

**Comment by nismojkee** [comment]
Any time I meet same issue but with zip archive (~3mb)

**Comment by chermoso** [comment]
Same here with zip files, and it's difficult to prevent because it happens sometimes
