### ISSUE TITLE
Chrome, malicious file warning when adding .js files

### ISSUE THREAD

**Issue by Blackbaud-JasonRikard** [Stuk/jszip#263]
When adding a file with a .js extension, Chrome Version 48.0.2564.116 (64-bit) (OSX) is blocking the download. If I change the extension to .html, the archive will download. This is regardless of the content of the JS file. It is working as normal on Firefox.  I've tried from localhost, and two separate domains. Any suggestions? [This](http://stackoverflow.com/questions/9512919/getting-around-chromes-malicious-file-warning) seems to be the most relevant information I can find.

```
var zip = new JSZip();
var templateFolder = zip.folder('js');
templateFolder.file('anyfile.js',  'any string');
location.href="data:application/zip;base64," + zip.generate({type: "base64"});
```
![screen shot 2016-02-29 at 10 20 49 am](https://cloud.githubusercontent.com/assets/11817620/13398868/525b09d2-dece-11e5-8aca-0c7f6d6b0ed0.png)

**Comment by Blackbaud-JasonRikard** [comment]
Using the [file-saver.js](https://github.com/eligrey/FileSaver.js) polyfill resolves this problem:

```
var content = zip.generate({type:"blob"});
saveAs(content, "download.zip");
```

I'm suspecting that it's possible to not use the polyfill if I can figure out how to download the contents of `zip.generate({type: "blob"})`.

**Comment by dduponchel** [comment]
You can take a look at the source code of the polyfill for this. I think [blob urls](http://caniuse.com/#feat=bloburls) (see [here](https://github.com/eligrey/FileSaver.js/blob/04f232f658b0d70cad0a2bebf5a514de2deab40a/FileSaver.js#L142)) *should* work everywhere (on recent browsers) but I have some doubts about safari (also, don't forget `URL.revokeObjectURL()`).

**Comment by Blackbaud-JasonRikard** [comment]
Thank you! I'll stick with using file-saver.js so I won't have to sort out the details as they have already done.
