### ISSUE TITLE
Uncaught error - missing ./correspondence module

### ISSUE THREAD

**Issue by mleczakm** [Stuk/jszip#267]
When loading page with DataTables and JSZip I'm getting this error on Chrome:
`Uncaught Error: Cannot find module './correspondence'`
or on Firefox
`Error: Cannot find module './correspondence'`
Commenting line 3951 changes it into
`Error: Cannot find module './zlib/correspondence'`
Commenting also lines 2810 and 3173 removes error.

**Comment by dduponchel** [comment]
I don't know any `correspondence` module. Which file are you updating ? Which version of JSZip are you using ?

**Comment by mleczakm** [comment]
from bower.json
`"name": "jszip",
"version": "2.5.0",`
filename - _jszip.js_

**Comment by dduponchel** [comment]
With a `bower install jszip#2.5.0` and a simple html file:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <script src="./bower_components/jszip/dist/jszip.js"></script>
    <script>
    console.log(JSZip);
    </script>
  </head>
</html>
```
I don't have any error.

On the line 3951 of `dist/jszip.js` I have
```js
var msg   = _dereq_('./messages');
```
so I don't know where this `correspondence` module comes from.

Do you have a small test case to reproduce your issue ?

**Comment by mleczakm** [comment]
Well, I've maid a terrible mistake, sorry fo bothering, closing...
