### ISSUE TITLE
nodebuffer bytelength limitation

### ISSUE THREAD

**Issue by huaSolna** [Stuk/jszip#276]
I have following code for generate zip file and response to my client side.
```javascript
var testStr =  '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Version xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" VersionId="2.0"><DetailedVersion>2.0 RC</DetailedVersion></Version>';

zip.file(example.xml, testStr);
var buffer = zip.generate({type:"nodebuffer"});
res.writeHead('Content-Length', buffer.byteLength);
// res.write(buffer, 'binary');
res.end(buffer, 'binary');
```

The problem for me is if `buffer.byteLength` greater then 239 bytes, then I can't open it, and get error `Error 1 - Operation not permitted.` on my Mac. Need help to find out what I did wrong.

console zip object:

```
 files:
   { 'bcf.version':
      { name: 'bcf.version',
        dir: false,
        date: Thu Apr 07 2016 11:49:05 GMT+0200 (CEST),
        comment: null,
        unixPermissions: null,
        dosPermissions: null,
        _data: '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Version xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" VersionId="2.0"><DetailedVersion>2.0 RC</DetailedVersion></Version>',
        options: [Object],
        _initialMetadata: [Object] } },
  comment: null,
  root: '',
  clone: [Function] }

```

**Comment by dduponchel** [comment]
A limit on 239 bytes is strange, I don't get it on my side. Which version of nodejs do you use ?

**Comment by huaSolna** [comment]
node/5.10.1 and node/5.2.0

Here is part of my client side, I have a string to byte helper.
```
function str2bytes (str) {          
  var bytes = [];
  for (var i=0; i<str.length; i++) {
    bytes[i] = (str.charCodeAt(i));
  }
  //console.log(bytes);
  return bytes;
}
$http.post('url', data).then(function(res){
  console.log(res);
  var data = new Blob([str2bytes(res.data)], { type: 'application/zip' });
  FileSaver.saveAs(data, 'topic.zip');
});
```

**Comment by dduponchel** [comment]
#### Server side:
If you run the following code, does it work ?
```js
var u8 = new Uint8Array(300);
for (var i = 0; i < 300; i++) {
  u8[i] = i % 256;
}

var buffer = new Buffer(u8, undefined);
console.log("length", buffer.length);
console.log("byteLength", buffer.byteLength);
```

The documentation don't say anything about a `buffer.byteLength`, I only see the [length](https://nodejs.org/api/buffer.html#buffer_buf_length) attribute. Could you test with `length` ?

#### Client side:
You should use `responseType: "arraybuffer"` in [$http.post](https://docs.angularjs.org/api/ng/service/$http#usage): by default, you will get a text, decoded from the current charset (I'd say UTF-8). The content is not a text and "decoding" it will corrupt it.

**Comment by huaSolna** [comment]
```javascript
$http.post('bcf/write', data, { responseType:'arraybuffer'}).then(function(res){
  var data = new Blob([str2bytes(res.data)], { type: 'application/zip' });
  FileSaver.saveAs(data, 'topic.zip');
});
```

- I replaced  `byteLength` to `length`. (console `length` is 300 as it should be).

-  I got lucky by using `responseType:"arraybuffer"`, the error console is gone, when I try to open the file, but I got a .cpgz file, and repeat .zip and .cpgz inside each other.

**Comment by huaSolna** [comment]
@dduponchel thanks, i final find out the reason.  `responseType:"arraybuffer"` is the KEY. And simply put arraybuffer in to `Blob`, there is no need to convert str2byte.
