### ISSUE TITLE
Mismatch for "accumulate(callback [,updateCallback])"

### ISSUE THREAD

**Issue by CVex2150J** [Stuk/jszip#283]
Just a quick mention.
There is a mismatch between the documentation for accumulate and the actual code.
StreamHelper.accumulate() takes only 1 parameter in the actual code. 
##### Cause of the mistake ?!?! #####
``` javascript
function accumulate(helper, updateCallback) {
    return new external.Promise(function (resolve, reject){
        var dataArray = [];
        // [...]
```
##### Actual Code #####
```javascript
StreamHelper.prototype = {
    /** **/
    accumulate : function (updateCb) {
        return accumulate(this, updateCb);
    },
```

**Comment by dduponchel** [comment]
Nice catch !
The early version of `accumulate` [did](https://github.com/Stuk/jszip/blob/0ceb14c2eeab8ecb46e6d9bf891ed7bd6b768965/lib/stream/StreamHelper.js#L184) take two callbacks but I missed the documentation when refactoring it to return a Promise.
I'll re-check the documentation this weekend.
