### ISSUE TITLE
How can I zip a mp4 video file?

### ISSUE THREAD

**Issue by carloscarcamo** [Stuk/jszip#286]
I'm trying to zip a mp4 video from remote URL, is this possible? any advice?

thanks in advance!

**Comment by dduponchel** [comment]
In a browser or with nodejs ? Either way, you should see the [relevant part of the documentation](https://stuk.github.io/jszip/documentation/howto/read_zip.html).
MP4 files are already compressed so you can skip the compression (compression = `STORE`, the default) here.

**Comment by jimmywarting** [comment]
close now?

**Comment by waylander47** [comment]
Hi guys,

I have the same issue. @carloscarcamo I would like to know if you have found a solution ?

Thanks in advance.
Best regards.

**Comment by dduponchel** [comment]
Without response from @carloscarcamo, I'm closing this one. @waylander47: could you create a new issue with more details (what you're trying to do, where you're stuck at, etc) ?

**Comment by waylander47** [comment]
Ok here is the solution to do it on locals mp4 videos :
`var fileURL = URL.createObjectURL(localFile)
JSZipUtils.getBinaryContent(fileURL, function (err, data) {
					if(err) {
						console.log(err); // or handle the error
					}
					var zip = new JSZip();
					zip.file("video.mp4", data, {binary:true});
					zip.generateAsync({type:"blob"}).then(function (blob) {
						saveAs(blob, "archive.zip");
					}, function (err) {
					  console.log(err);
					});

				});`
