### ISSUE TITLE
Problem with the documentation of generateNodeStream end event

### ISSUE THREAD

**Issue by toto42** [Stuk/jszip#293]
Hello,

I think there is a problem I struggled with way longer that I would like to admit with the documentation.
In the [documentation](https://stuk.github.io/jszip/documentation/api_jszip/generate_node_stream.html) the following example is given:

> zip
> .generateNodeStream({streamFiles:true})
> .pipe(fs.createWriteStream('out.zip'))
> .on('end', function () {
>     console.log("out.zip written.");
> });

However, in the node [documentation](https://nodejs.org/api/stream.html#stream_class_stream_writable), `fs.createWriteStream()` seems to send `stream.Writable`'s events, and I don't see an `end` event but there is a `finish` event.
When testing with the `end` I can't make it to work but when I replace the event with a `finish` it does works.

I make an issue about that in case someone else run into this problem too. :)

Have a nice day!

**Comment by dduponchel** [comment]
Nice catch !
You're right, the `end` event is emitted by readable streams while `finish` is emitted by writable streams.
The following code illustrate it:
```js
zip
.generateNodeStream({streamFiles:true})
.on('end', function () {
  console.log("zip stream ended.");
})
.pipe(fs.createWriteStream('out.zip'))
.on('finish', function () {
  console.log("out.zip written.");
});
```

The documentation is also wrong on other pages (every page with a `fs.createWriteStream`).

**Comment by toto42** [comment]
Thanks for the fix, and thanks for the lib. :)
I hope it will help other people to not get confused in the future! :)
