### ISSUE TITLE
Cannot assign to read only property 'extend'

### ISSUE THREAD

**Issue by delashum** [Stuk/jszip#294]
I am running jszip v3.0.0, and node v5.11.1 and for some reason this error started popping up. I have tried downgrading node, removing, reinstalling and updating (from 2.6.0 to 3.0.0) jszip, and a variety of things. However, everytime I try and start up my server I get this error if I `require('jszip')` somewhere in my code:

`..../node_modules/jszip/lib/utils.js:398`
`exports.extend = function() {`
`^`

`TypeError: Cannot assign to read only property 'extend' of #<Object>`
`at Object.<anonymous> (..../node_modules/jszip/lib/utils.js:398:16)`

Is this a bug? Or do I have something setup incorrectly?

**Comment by dduponchel** [comment]
I can't reproduce the issue: with
```js
console.log("using node", process.version);
var JSZip = require("jszip");
var zip = new JSZip();
console.log("zip is", zip);
```
I get
```
$ nvm use v5.11.1
Now using node v5.11.1 (npm v3.8.6)
$ node index.js 
using node v5.11.1
zip is { files: {}, comment: null, root: '', clone: [Function] }
```

What does this snippet prints on your side ?

We can rename the function but I'd like to understand the cause of the issue.

**Comment by delashum** [comment]
Hmm.. I also get 
```
$ node index.js 
using node v5.11.1
zip is { files: {}, comment: null, root: '', clone: [Function] }
```

Which leaves me more confused. Do you have any idea what could be causing the error I am getting above? It looks like JSZip is working find when you run it that way.
I am using JSZip indirectly as a module of a module I am using. Possibly the issue lies with the main module I am using. However, the error directed me to JSZip, so I would assume that the issue is with that.

So strange..

**Comment by edi9999** [comment]
I guess one possibiility would be that someone in the middle defines an extend method on the Object prototype, and set is as readonly. grep for extend in all your source files, maybe you can find the culprit

**Comment by delashum** [comment]
Okay, I'll look around, and let you know.
The middle module I'm using is actually your docxtemplater. It's strange that you have never seen this before.
Anyways, as I said, I'll look around and post back when I find something out.

Thanks for the replies.
