### ISSUE TITLE
Suggestion: version nr in file header dist files

### ISSUE THREAD

**Issue by jrfnl** [Stuk/jszip#299]
It would be helpful to have the version nr of the release in the file header of the files in the `dist` folder.
Quite often, either one of those will be the only file included with an external project and there's no way to identify the version based on the file itself without having to resort to blunt force file compares.

Oh and while you're at it, you may want to update the copyright line as well with 2016 ;-)

```js
/*!

JSZip v 3.0.0 - A Javascript class for generating and reading zip files
<http://stuartk.com/jszip>

```

**Comment by dduponchel** [comment]
Indeed. Having this version in `JSZip.version` for example should be useful too.
