### ISSUE TITLE
iterate over list of files only in specific folder

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [Stuk/jszip#301]
Hi,

with ```forEach``` I can iterate over all objects in a zip file. Can I also somehow iterate only over the objects in a specific folder? Or over folders?

Thanks!

**Comment by dduponchel** [comment]
`forEach` uses the current folder, see the example [in the documentation](https://stuk.github.io/jszip/documentation/api_jszip/for_each.html).
```js
// with zip containing
// - file1.txt
// - my_folder/file2.txt
zip.folder("my_folder").forEach(function (relativePath, file) {
  console.log("relative path:", relativePath, "file full path:", file.name);
});
// will print:
// relative path: file2.txt file full path: my_folder/file2.txt
```

Does this answer your question ?

**Comment by RudolfVonKrugstein** [comment]
Oh, I meant over all files in a specific folder, but NOT in a subfolder.

So if I have this structure:

```
topdir1/
- file1.txt
- file2.txt
- dir1/
- - deepdir/File2.txt
topdir2/
```

Can I make an iterate only over the files directly in topdir1 ```[file1.txt, file2.txt]``` or maybe including the folder ```[file1.txt, file2.txt, dir1]```

Why do I want this? I have a zip file with a huge number of files, but I want to know:

1. What are the top level directories (which are only a few)
2. What are the files in the top level directory (which are also only a few)

So I could iterate over everything and filter the result. But that sounds inefficient if I just want the things listed above.

**Comment by dduponchel** [comment]
Not with the current API. JSZip stores everything in a map-like object, your example looks like
```js
zip.files = {
  "topdir1/": {...},
  "topdir1/file1.txt": {...},
  "topdir1/file2.txt": {...},
  "topdir1/dir1/": {...},
  "topdir1/dir1/deepdir/": {...},
  "topdir1/dir1/deepdir/File2.txt": {...},
   // ...
}
```
We need this representation, some file formats only see "entries" and not "folders and files" (and will break with intermediary folders).

Performance wise, JSZip must iterate over everything and can't do better than a filter on your side.

**Comment by RudolfVonKrugstein** [comment]
Ok, that is good to know. Thanks!
Nathan
