### ISSUE TITLE
uncompress bytes

### ISSUE THREAD

**Issue by sfornengo** [Stuk/jszip#306]
Before v3.0.0 I was using the following command:
JSZip.compressions.DEFLATE.uncompress(bytes)
to uncompress bytes to a uint8 array.
How to upgrade this line in v3.0.0 ?

**Comment by dduponchel** [comment]
The internals of JSZip changed in v3 and we don't work on the full content anymore.
If you whish to inflate compressed content like that, you should use [pako](https://github.com/nodeca/pako/) directly ([which was behind](https://github.com/Stuk/jszip/blob/v2.6.0/lib/flate.js#L15) the `uncompress` method).
