### ISSUE TITLE
Strange behaviuor with compression:"DEFLATE" and long text.

### ISSUE THREAD

**Issue by JackAubrey** [Stuk/jszip#307]
First of all excuse me about my bad English.
I found a strange behaviour if I enable the compression (compression: "DEFLATE") with a long text.
This is my scenario:
I have the necessity to take some DOM's elements (some tables in particular, those ones contains a lot of data and can contains nested tables) stringify them, compress with jsZip and than send the results to server side.
So! In "generateAsync" function, I send the base64 received into this function to my java server-side code in order to transform the HTML received into a PDF.
In the Java side, the unzip is well done but the content looks strange.
After 2000 chars there is a long white block.
If I use simple "compression:STORE" this behaviour doesn't occur.

In first instance I thought there was some strange thing in my data (I found the corruption near to URLs or emails contained into my html tables) but after some tests (I removed all kind of URL, email and so on) I discovered that it depends from the lenght of text.
I have splitted the text into 500/1000 bytes blocks and server side rebuilt the entire text.
Using this splitting text workaround, this strange behaviour doesn't occur anymore.

Looking at my unzipped data, white block appears around 2000 chars, so you can see this kind of behaviour only when you have a massive source text.

Briefly to reproduce this problem:
Client side:

```js
var zip = new JSZip();

$.each($(".myTables"), function(i,v){
    var sTable = $('<table>').append($(this).clone()).remove().html();
    // consider this: in my case there could be from 4 to 6 tables which contains a lot of data. Total text length was more than 50k
    zip.file("aname_"+i, sTable);
    // zip.file("aname_"+i, sTable, {binary: true}); // i tried to use both version
});

zip.generateAsync({type:"base64", compression:"DEFLATE", compressionOptions : {level:6}}).then(function (base64) {
  $("#toExport").val(base64);
  $("#myForm").submit();
});
```

ServerSide:
```java
byte [] zipBytes = Base64.decodeBase64(getToExport());
ZipInputStream zipStream = new ZipInputStream(new ByteArrayInputStream(zipBytes));
ZipEntry entry;
StringBuffer html = new StringBuffer(5000);

while( (entry = zipStream.getNextEntry()) != null)
{
  byte [] buffer = new byte[(int)entry.getSize()];
  zipStream.read(buffer);
  html.append(new String(buffer));
}
```

at the end, the html var contains data plus a white block if the sent data length is massive but not if I split it in less than 2000 chars segments.

Thanks for your great jsZip

**Comment by dduponchel** [comment]
I tried generating a zip file as a base64 with 6 files of 50KB each (in a browser) and I can't reproduce your issue.

In your browser, could you save the base64 (use a `textarea` or use `saveAs` for example) instead of submitting the form ? Then, decode the base64 and check the content of the zip file.
That way, we will know if the root cause is somewhere in your browser or somewhere between the `$("#myForm").submit()` and the java code.

**Comment by JackAubrey** [comment]
Hi dduponchel .
First of all, thanks for your support and excuse me if I reply only now .

You can close this my issue. **There is no bug in your own library** .
After plenty tests , I discovered the cause of my bug.
This one occurred because I tried to read the entire ZipEntry in a single pass, using a byte array with the ZipEntry size.
This single read operation of all entry  causes that error .
I do not know why, but with simply STORE Zip, this problem does not occur.

I changed the code. Now i read the ZipEntry in a loop to read stream data blocks.

Thanks for all support and excuse me for this my mistake

**Comment by dduponchel** [comment]
You're welcome :)
