### ISSUE TITLE
Solution to writing large zip's in browsers

### ISSUE THREAD

**Issue by jimmywarting** [Stuk/jszip#308]
[StreamSaver.js](https://github.com/jimmywarting/StreamSaver.js) uses the [w3c Stream API](https://streams.spec.whatwg.org/) and isn't so different from the node version. streams is all good and that but it also solves another problem, which is memory, this will also write to the hard drive from the browser all **asynchronous** 

Thought you would be interested in [StreamSaver.js](https://github.com/jimmywarting/StreamSaver.js).
I have been able to write 16+ GB of data to the disk without any problem

One gotcha is: it only works in Chrome and Opera

can solve issues like #5 #227 #343

**Comment by from2001** [comment]
Could you put snippet using JSZip and StreamSaver.js? How can I handle data from generateInternalStream with StreamSaver.js?

I have a problem to create large 1GB zip in blob format, and would like to store generated zip in persistent storage with chrome.

**Comment by jimmywarting** [comment]
You don't need StreamSaver to save it in chrome's persistent storage. StreamSaver saves data directly to the hard drive

**Comment by from2001** [comment]
I tried to save zip file into persistent storage using the following code, but generate zip file is broken.
How can I save large zip in persistent storage?
Blob file size limit is 500MByte, so I couldn't find out how.

`function streamWriteToZip(data){
	//console.log(data);
	console.log("x");
	gFileEntry.createWriter(function(fileWriter) {
		var blob = new Blob([data.buffer], {type: "application/octet-binary"})
		fileWriter.seek(fileWriter.length);
		fileWriter.write(blob);
	}, errorHandler);
}

function errorHandler(e) {
  var msg = '';
  switch (e.code) {
    case FileError.QUOTA_EXCEEDED_ERR:
      msg = 'QUOTA_EXCEEDED_ERR';
      break;
    case FileError.NOT_FOUND_ERR:
      msg = 'NOT_FOUND_ERR';
      break;
    case FileError.SECURITY_ERR:
      msg = 'SECURITY_ERR';
      break;
    case FileError.INVALID_MODIFICATION_ERR:
      msg = 'INVALID_MODIFICATION_ERR';
      break;
    case FileError.INVALID_STATE_ERR:
      msg = 'INVALID_STATE_ERR';
      break;
    default:
      msg = 'Unknown Error';
      break;
  };

  console.log('Error: ' + msg);
}

var gfs;
var gFileEntry;
gfs.root.getFile('log.zip', {create: true}, function(fileEntry) {gFileEntry=fileEntry;
zip.generateInternalStream({type: 'uint8array', streamFiles: true})
.on('data', data => streamWriteToZip(data))
}, errorHandler);

window.requestFileSystem  = window.requestFileSystem || window.webkitRequestFileSystem;
navigator.webkitPersistentStorage.requestQuota(1024*1024*5, 
  function(gB){
  window.requestFileSystem(PERSISTENT, gB, onInitFs, errorHandler);
}, function(e){
  console.log('Error', e);
})
function onInitFs(fs) {
  gfs = fs;
}`

**Comment by jimmywarting** [comment]
```javascript
// This worked for me 
navigator.webkitPersistentStorage.requestQuota(102410245, gB => {
  webkitRequestFileSystem(PERSISTENT, gB, onInitFs, console.error)
}, console.error)

function onInitFs(fs) {
  fs.root.getFile('log.zip', {create: true}, fileEntry => {
    fileEntry.createWriter(writer => {
      writer.seek(writer.length)
      zip.generateInternalStream({type: 'uint8array', streamFiles: true})
      .on('data', data =>
        writer.write(new Blob([data])
      )
    }, console.error)
  }, console.error)
}
```

**Comment by from2001** [comment]
jimmywarting,
Your code had some syntax error, so I fixed it.

However, I got InvalidStateError at writer.write(new Blob([data])); What do you think is the problem?

> Uncaught InvalidStateError: Failed to execute 'write' on 'FileWriter': An operation that depends on state cached in an interface object was made but the state had changed since it was read from disk.

One more question.
writer.seek(writer.length) is located outside writer.seek(writer.length). Shouldn't this be located right  before writer.write(new Blob([data])?

	navigator.webkitPersistentStorage.requestQuota(102410245, gB => {
	  webkitRequestFileSystem(PERSISTENT, gB, onInitFs, console.error)
	}, console.error)

	function onInitFs(fs) {
	  fs.root.getFile('log5.zip', {create: true}, fileEntry => {
	    fileEntry.createWriter(writer => {
	      	writer.seek(writer.length);
	      	console.log(0);
		zip.generateInternalStream({type: 'uint8array', streamFiles: true})
		.on('data', data => {
			writer.write(new Blob([data]));
		})
		.resume()	
	    }, console.error)
	  }, console.error)
	}

**Comment by from2001** [comment]
jimmywarting,
I found the way to avoid InvalidStateError. We need to wait till writing data is done. I added some codes to wait. However, generated zip file seems broken. 

	// This worked for me 
	navigator.webkitPersistentStorage.requestQuota(102410245, gB => {
	  webkitRequestFileSystem(PERSISTENT, gB, onInitFs, console.error)
	}, console.error)

	function onInitFs(fs) {
	  fs.root.getFile('log8.zip', {create: true}, fileEntry => {
	    fileEntry.createWriter(writer => {
		zip.generateInternalStream({type: 'uint8array', streamFiles: true})
		.on('data', function(data) {
			writer.seek(writer.length);
			writer.write(new Blob([data]));
			this.pause();
			var gThis = this;
			writer.onwriteend = function () {
				gThis.resume();
			}
		})
		.resume()
	    }, console.error)
	  }, console.error)
	}

**Comment by SamBallantyne** [comment]
Hey @jimmywarting. I'm getting error using your code:
`Failed to execute 'write' on 'FileWriter': An operation that depends on state cached in an interface object was made but the state had changed since it was read from disk.` Any ideas?

**Comment by SamBallantyne** [comment]
Hey @from2001 did you ever find a solution?

**Comment by preranaB** [comment]
Hey @jimmywarting Could you please help me on this:- https://github.com/Stuk/jszip/issues/493

**Comment by zipzapduo** [comment]
Me too.

**Comment by jimmywarting** [comment]
I can help if you hook me up somehow in a chat (gitter) or a Collaborate jsfiddle

**Comment by rdo182** [comment]
@jimmywarting @zipzapduo 

Hi guys! Found some solution? I'm with the same problem.

**Comment by jimmywarting** [comment]
@rdo182 there are some solution floating around in #343 by using node's web streams

**Comment by rdo182** [comment]
Thanks @jimmywarting!

I ended up changing the lib to zip the files, because of the little time I have and why when I try to partition the files, something like files up to 250 Mb the lib sends me the 250Mb files and one with all the files of each file with 250Mb.
