### ISSUE TITLE
generateAsync does not work on Node.js 6.2.2

### ISSUE THREAD

**Issue by Lsaes** [Stuk/jszip#310]
The generateAsync method does not work on Node.js 6.2.2. Then promise that is returned is never called. 

A demonstration: https://www.youtube.com/watch?v=HMXykAhBfuM&feature=youtu.be . 

Test code:

```
var JSZip = require('jszip');

try {
  var zip = new JSZip();
  zip.file("Hello.txt", "Hello World\n");
  console.log('Start generateAsync');

  zip.generateAsync({type: "blob"})
    .then(function (content) {
      console.log('Stop generateAsync');
      console.log(content);
    });
} catch (ex) {
  console.log(ex);
}
```

**Comment by Lsaes** [comment]
I found the problem, there was no error given by jszip. Blob is not supported on my platform. I solved this issue by using the type string.

**Comment by edi9999** [comment]
This issue can be closed

**Comment by pankajmalkani** [comment]
from where i should find the type nodebuffer. thanks and regards

**Comment by coportian-harshit** [comment]
Hello, I am using node 6.11.1 and trying to zip an array of links, but it so happens that sometimes it zips the complete ones but sometimes, it does not do for all the links.

Any help or redirect to links would be helpful. Thanks
