### ISSUE TITLE
Current documentation

### ISSUE THREAD

**Issue by photopea** [Stuk/jszip#313]
Hi,

where can I find the current documentation? It seems like the documentation at your web describes features, which do not work.

**Comment by dduponchel** [comment]
The documentation is [here](https://stuk.github.io/jszip/) and should be up-to-date. Which feature doesn't work ?

**Comment by photopea** [comment]
E.g. [here](https://stuk.github.io/jszip/documentation/howto/read_zip.html) you describe creating a new JSZip(data), but the latest version seems to have the constructor without parameters.

**Comment by dduponchel** [comment]
It was fixed by #298 but I forgot to update the documentation website... It's up-to-date now, thanks for the bug report !
