### ISSUE TITLE
Can't read image file starting with filename that begins with a '.'

### ISSUE THREAD

**Issue by volx7577** [Stuk/jszip#314]
I'm using the library to unzip a folder that contains a directory, in which there is an image file with a name of the pattern ".filename.png"
Other files in the zip are read correctly, but it appears as if the 'dot file' is getting ignored.
Is this functionality supposed to exist?

**Comment by dduponchel** [comment]
No, JSZip doesn't filter out "hidden" files. Can you share a file that shows the issue with the code you use ?

**Comment by volx7577** [comment]
Hi, I haven't been around the Windows computer I had used to test this (it isn't an issue on Mac because a user cannot create hidden files). I can send you a test file tomorrow.
When you say it doesn't filter out hidden files, do you mean that it makes no distinction between hidden and regular files, or that it is not built to process hidden files?

**Comment by dduponchel** [comment]
I mean that JSZip makes no distinction between `filename.png` and `.filename.png`, you should be able to process them the same way.

**Comment by dduponchel** [comment]
@volx7577 any news ?

**Comment by volx7577** [comment]
Hi, 
I found that it was actually some hidden files that Mac OS puts in a zip folder that was tripping up my code, not the dot-image file in question.
thanks.
