### ISSUE TITLE
Update pako to 1.0.2

### ISSUE THREAD

**Issue by puzrin** [Stuk/jszip#320]
https://github.com/nodeca/pako/issues/78

Bug is in deflate, inflate not affected. No problem if jszip used as node npm module, but i strongly recommend to update browserified builds. Probably, it also worth to backport this to 2.x and 1.x versions if those are used wide.

Pako's mainstream version is now 1.0.2 (semver). 0.2.9 is equal to 1.0.2 and released to give change to old dependents.

**Comment by dduponchel** [comment]
JSZip v1 is 3 years old and don't use pako, I think we can skip it. I'll prepare a fix + release for the v2, the v3 should get a release soon anyway.

Thanks for the issue.

**Comment by dduponchel** [comment]
Fixed and released in v2.6.1 and v3.1.0.
