### ISSUE TITLE
Add zip file into JSZip()

### ISSUE THREAD

**Issue by amou1012** [Stuk/jszip#323]
I want to add multiple zip files into JSZip() , and the content type I use is nodejs : 
zip.file(filename, fs.readFileSync(filename));

but when I use the following code : 

 zip.generateAsync({type:"nodebuffer"}).then(function (content) {
    saveAs(content, "Test.zip");
});

Nothing happens and it doesn't pop up a download interface. The environment is Chrome and it is the latest version

Need help , Thanks a lot .

**Comment by dduponchel** [comment]
I'm confused: is this in nodejs or in chrome ? `fs.readFileSync` only works in nodejs and `saveAs` only works in a browser.

You should try 
```js
zip.generateAsync({type:"nodebuffer"}).then(function (content) {
  saveAs(content, "Test.zip");
}).catch(function (e) {
  console.error(e);
});
```

The `.catch()` should show you the error.

If you are in nodejs, you should see a `ReferenceError: saveAs is not defined`: in nodejs, you should do something like:

```js
zip
.generateNodeStream({type:'nodebuffer',streamFiles:true})
.pipe(fs.createWriteStream('out.zip'))
```

See [this page](http://stuk.github.io/jszip/documentation/howto/write_zip.html#in-nodejs) for more informations.

On a related note, `fs.readFileSync` may not be the most efficient way to load a file in JSZip (you will load everything in memory and block the execution thread). See [this page](http://stuk.github.io/jszip/documentation/howto/read_zip.html#in-nodejs): `zip.file(filename, fs.createReadStream(filename));` is more efficient.

**Comment by jitendra-khatri** [comment]
Hello @dduponchel , any luck with this?

**Comment by dduponchel** [comment]
Without response from @amou1012, I'm closing this one. @jitendra-khatri: could you create a new issue with more details (what you're trying to do, where you're stuck at, etc) ?
