### ISSUE TITLE
JSZip.loadAsync() not working in Meteor

### ISSUE THREAD

**Issue by b-nugent** [Stuk/jszip#334]
So I'm trying to take in a zip file from the client, using a simple input tag, and I'd like for the server to open up the zip, take a look at it's contents and then put each file in a slot in an array (so that I can deal with them one by one later on). The problem is that loadAsync will not work on my zip file no matter what I try. Somewhere the zip and its contents are becoming undefined making it impossible to get something out at the end. Here is the code I'm dealing with.

This is the client side code, basically it takes in the file from the html page and sends it to the server:

```
Template.Home.events({
	'change #fileImporter': function(event) {
		Meteor.call("read", event.target.files, function(error, result) {
			if(error) {
				console.log("It Failed: " + error);
			} else {
				console.log("Results: " + result);
			}
		});
	}
});
```

The server side then takes that file and tries opening it and running through its contents:
```
Meteor.methods({
	read: function(file) {
		var JSZip = Meteor.npmRequire('jszip');

		var entries = [];

		for(var i = 0; i < file.length; i++) {
			JSZip.loadAsync(file[i]).then(function(zip) {
				zip.forEach(function (relativePath, zipEntry) {
					entries.push(zipEntry.name);
				});
			});
		}
	
		return entries;
	}
});
```

Everything I wrote is based on the examples I've seen and theoretically it should work, however in practice I get absolutely nothing. I am not even getting an error. Just curious if it is possible to do in Meteor, or if I am writing this code all wrong.

**Comment by dduponchel** [comment]
The `loadAsync` method is asynchronous and returns a promise. The `then` callback will be called **after** you returned from the `read` method. This method needs to be async too, either returning a promise or accepting a callback.

I would do the following:
```js
/*
 * transform file (a list of binary content)
 * into a list of promises of JSZip instances (map(JSZip.loadAsync))
 * into a promise of list of JSZip instances (Promise.all)
 */
var zipsPromise = Promise.all(file.map(JSZip.loadAsync));

var entriesPromise = zipsPromise.then(function (zips) {
  var entries = [];
  // for each zip, we extract the entries
  zips.forEach(function (zip) {
    zip.forEach(function (relativePath, zipEntry) {
      entries.push(zipEntry.name);
    });
  });
 
  // we chain the promise with the entries
  return entries;
});

// you can return entriesPromise from the function and use it like this outside:
entriesPromise.then(function (entries) {
  // ...
}).catch(function(e) {
  // handle the error e
});
```

**Comment by b-nugent** [comment]
Thank you for addressing my issue so quickly. So I implemented your solution and now my program is getting caught up on the map function. Apparently the zip file isn't coming in as an array so when it reaches the map function it spits out an error saying: 

> TypeError: Object [object Object] has no method 'map'

I'm confused as to what is causing such a roadblock when the process itself seems very straightforward. I take in the file using `<input type=file>`, I then have my event handler pass `event.target.files` into the function you wrote (where the `file` variable in the function is that passed zipped file).

**Comment by dduponchel** [comment]
`file` might be a [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) which is not a real array but looks like one. If your `for(var i = 0; i < file.length; i++)` worked, you can replace the `map` with it.

As long as you call `JSZip.loadAsync` with a supported binary content (Blob, Uint8Array, etc), it should work. [This example](https://github.com/Stuk/jszip/blob/v3.1.1/documentation/examples/read-local-file-api.html#L68) is similar to what you're doing.

**Comment by b-nugent** [comment]
I found that what I am receiving is a `FileList`, so I've started to try another approach, I'll keep updates posted as I try to work out a solution.

**Comment by b-nugent** [comment]
After spending time on other functionality I eventually came back to this issue and I have found a solution. The first thing to note, is that if you are going to unzip a folder in Meteor, do not send the imported file to the server because when you pass that `File` through, it immediately becomes `null`. Also, I was using a Meteor package version of JSZip, and when I switched to a [Node package](https://www.npmjs.com/package/jszip) I was able to use the JSZip functionality on the client. Here is my solution: 
```
Template.Home.events({
	'change #fileImporter': function(event) {
		event.preventDefault();

		var JSZip = require("jszip");

		JSZip.loadAsync(event.target.files[0]).then(function(zippedFile) {
			var entries = [];

			zippedFile.forEach(function (relativePath, fileEntry) {
            	entries.push(fileEntry);
            });
		});
	}
});
```

As you can see, the solution was very straightforward. The only thing that gave me grief was the fact that I was passing the `File` object to the server and also using a Meteor package for the JSZip functionality. 

Thanks @dduponchel for helping me wrap my head around how JSZip should be implemented!

**Comment by juvyc** [comment]
@b-nugent 

hi... how you handle to save it on the server or directory after you extract the files inside zip? Can you share?

Thanks

**Comment by b-nugent** [comment]
After successfully uploading the file onto the server, I parse the data in the file and save it into a collection. Once I've finished parsing all of that information I make sure to remove the file I initially uploaded (I don't like keeping that kind of stuff around if I don't need it anymore). Hope that helps!
