### ISSUE TITLE
simple file-in-folder example results in invalid zip file

### ISSUE THREAD

**Issue by patrickkettner** [Stuk/jszip#339]
hey there!

When I run the following on v3.1.1 (with node v6.3.1)

```js
var JSZip = require('jszip');
var zip = new JSZip();

zip.file("test/Hello.txt", "Hello World\n");

zip.generateNodeStream({type:'nodebuffer',streamFiles:true})
  .pipe(fs.createWriteStream('out.zip'))
```

I get the following when trying to open the zip file in Finder on macOS Sierra

![image](https://cloud.githubusercontent.com/assets/465414/17839925/f4b68c62-67c5-11e6-8b79-a2ea66e7e632.png)

Is this a bug or am I doing something silly?

**Comment by dduponchel** [comment]
Your code looks ok (and generates the expected zip file on my side). Can you try the following:
```bash
file out.zip
unzip -t out.zip
```
and post the output ?

**Comment by dduponchel** [comment]
An other question: in `node_modules/jszip/lib/generate/ZipFileWorker.js`, if you replace (line 203 and 204)
```js
// version needed to extract
header += "\x0A\x00";
```
by
```js
// version needed to extract
header += "\x14\x00";
```

Do you still get the error ?

**Comment by patrickkettner** [comment]
```
$ file out.zip 
out.zip: Zip archive data, at least v1.0 to extract

$ unzip -t out.zip
Archive:  out.zip
    testing: test/                    OK
    testing: test/Hello.txt           OK
No errors detected in compressed data of out.zip.

$ #for good measure
$ zip -FF ./out.zip --out ./out.fixed.zip
Fix archive (-FF) - salvage what can
 Found end record (EOCDR) - says expect single disk archive
Scanning for entries...
 copying: test/ 
        zip warning: no end of stream entry found: test/
        zip warning: rewinding and scanning for later entries
        zip warning: zip file empty
```

**Comment by patrickkettner** [comment]
> Do you still get the error ?

Yep - same issue after changing the line

**Comment by dduponchel** [comment]
`zip warning: no end of stream entry found: test/`: a folder shouldn't be streamed. Could you check with my branch [issue_339](https://github.com/dduponchel/jszip/tree/issue_339) ?
I reproduced this warning on my side and fixed it on this branch.

**Comment by patrickkettner** [comment]
yep! that fixes it for me :D

**Comment by dduponchel** [comment]
Cool ! I'll prepare a pull request then.
