### ISSUE TITLE
instructions for ES6 import

### ISSUE THREAD

**Issue by johanneswilm** [Stuk/jszip#349]
Neither of these work:
```
import {JSZip} from "jszip/dist/jszip"
```
or
```
import {JSZip} from "jszip/lib/index"
```

Any other suggestions? Could this be added to the instructions?

**Comment by johanneswilm** [comment]
figured it out.This works:

```
import JSZip from "jszip"
```

**Comment by ishandutta2007** [comment]
> figured it out.This works:
> 
> ```
> import JSZip from "jszip"
> ```

please add it to docs, even I had to hunt for the es6 syntax.
