### ISSUE TITLE
hi, nice work. I just want to know whether jszip can read files compressed with 7zip?

### ISSUE THREAD

**Issue by sternh** [Stuk/jszip#352]

**Comment by sternh** [comment]
Currently I can read zip files . When reading 7z files. I got following error:
jszip.min.js:13 Uncaught (in promise) Error: Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html(…).

Same files can be compressed to half size using 7z format compares to using zip format. So 7z files is more useful in internet.

**Comment by dduponchel** [comment]
`.zip` files created by 7z can be read, `.7z` files created by 7z can't.
These are two different formats and JSZip only support/focus on zip files.

**Comment by sternh** [comment]
Thanks.
Hope someday,  jszip can read .7z files either!
