### ISSUE TITLE
read the content of a zip file

### ISSUE THREAD

**Issue by GiacomoK** [Stuk/jszip#353]
Hi,
I use this code to download a zip from the web and read that, but I do not know what I have to do after that:

    $http.post(url, data, {responseType: 'arraybuffer'})
        .then(function successCallback(file_response) {
          var file = new Blob([file_response.data], {type: 'application/zip'});
          var zip = new JSZip();
          zip.loadAsync(file)
            .then(function (content) {
                // use content
            });
        }, function errorCallback(file_error) {
        });

What can I do with "content"? I need to open it and read the content of the files (actually I have always one file). How can I do that?

Thanks.

**Comment by dduponchel** [comment]
`content` is actually the up-to-date `zip` object: you use [file(name)](https://stuk.github.io/jszip/documentation/api_jszip/file_name.html) to get the entry then [async](https://stuk.github.io/jszip/documentation/api_zipobject/async.html) to get the full content for example.

```js
zip.loadAsync(file).then(function (content) {
  zip.file("my_file.png").async("uint8array").then(...);
})
```

If you only have one file, you can also chain promises directly:

```js
JSZip.loadAsync(file_response.data).then(function (zip) {
  return zip.file("my_file.png").async("uint8array");
}).then(function (pngContent) {
  // use the uint8array here
})
