### ISSUE TITLE
Zipping files created inside a callback

### ISSUE THREAD

**Issue by davejack1** [Stuk/jszip#354]
I totally got stuck in this problem related to callbacks.

Let me explain my case;

I have a library, which creates an SVG file. Since this SVG contains some text, I need to upload a font file and that needs an async function, hence the callback.

I create the SVG model but cannot take it out of the library; neither can return it, nor can assign it to a global variable.

Therefore, for example, I take the DIV element that I want to draw this SVG on and do the drawing to the specific DIV inside the callback (Actually I am using promise, but it is pretty much the same thing)

`document.getElementById(div).innerHTML = SVG`

Likewise, when I want to download this one SVG model, I do this inside the promise due to the fact that I cannot take my SVG model out of it.

This SVG model is parametric. So, I create several of them with different parameter values.

Now I want to save all those SVGs at once, with one button click. I concluded that zipping them inside a folder is the best approach.

First I need to define a JSZip object;

`var zip = new JSZip();`

Then I need to add each of those SVGs inside this zip file by using a for loop;

`zip.file("image1.svg", SVG);`

`zip.file("image2.svg", SVG);`

`zip.file("image2.svg", SVG);`
    
`and so on...`

The problem emerges at this point; This function of the library is called with specific parameter values to create an SVG and the resulting SVG is stuck inside the promise. I can assign it to a DIV, since DIV is already there and not treated like a variable created inside the JS (I assume).

But when it comes to assigning this SVG to global variable of `zip`, which is defined as `var zip = new JSZip();`, I cannot do it. 

If it was only one SVG file I want to zip, then I would do everything inside the promise, but several calls of the library function for generating different SVGs is required and the SVG I create from each call cannot go anywhere out of promise/callback.

Hope I clearly explained the problem.

How can I tackle this problem?

**Comment by dduponchel** [comment]
If I understand correctly, you have a function that generates a promise of a svg file:

```js
function generateSVG(name) {...}
generateSVG("image1").then(function(svg) {...});
```

JSZip supports (since v3) promises as input (as long as the promise contains the binary/text content you want to use):

```js
zip.file("image1.svg", generateSVG("image1.svg"), {binary:false});
zip.file("image2.svg", generateSVG("image2.svg"), {binary:false});
// ...
```

An other solution would be to wait for all promises:

```js
Promise.all([
  generateSVG("image1.svg"),
  generateSVG("image2.svg")
]).then(function (array) {
  var zip = new JSZip();
  zip.file("image1.svg", array[0], {binary:false});
  zip.file("image2.svg", array[1], {binary:false});
  // ...
})
```

Does this solve your issue ?

**Comment by davejack1** [comment]
Thank you, last approach solved my problem.
