### ISSUE TITLE
Showing image using JSZIP

### ISSUE THREAD

**Issue by gagandeepchhabda12305** [Stuk/jszip#355]
I have a zip located on my remote server. I want to show the images stored at that zip in my html file. I am able to load the zip file using JsZip. Could you help me with how can I show the image on the html page.

**Comment by dduponchel** [comment]
You can use a [blob url](http://caniuse.com/#feat=bloburls):

```js
zip.file("image.png").async("arraybuffer").then(function(content) {
  var blob = new Blob([content], {'type': 'image/png'})
  document.getElementById("my_png").src = URL.createObjectURL(blob);
});
```
An other solution is to use a data uri and base64 but it will be less efficient.

Does this solve your issue ?

**Comment by gagandeepchhabda12305** [comment]
I have used the combination of methods of loadAsync and async methods to obtain the image content in base64 and showed it on the browser
