### ISSUE TITLE
Support for File objects in zip.file() API

### ISSUE THREAD

**Issue by mikeal** [Stuk/jszip#367]
I noticed that [`zip.file()`](https://stuk.github.io/jszip/documentation/api_jszip/file_data.html) supports damn near every type ("String/ArrayBuffer/Uint8Array/Buffer/Blob/Promise/Nodejs stream" ) but doesn't support the [Web File API](https://developer.mozilla.org/en-US/docs/Web/API/File) which happens to be what I need to compress :)

**Comment by jimmywarting** [comment]
Think it's supported? File is a instance of blob, and we support blob so...
```javascript
zip.file('/sub/path/filename.txt', new File(["abc"], "filename.txt"))
```

**Comment by mikeal** [comment]
SWEET!
