### ISSUE TITLE
Download Issue for IE using jszip

### ISSUE THREAD

**Issue by dhruvin16** [Stuk/jszip#376]
I write a code to download multiple file as Zip in share point hosted app

```js
function create_zip() {
    var zip = new JSZip();
    
    $.each(filePathArray, function (i, path) {

        var filename = path; //"file" + i +".txt";
        var filee = path.substring(path.lastIndexOf('/') + 1);

        var fileURL = appweburl + "/_api/SP.AppContextSite(@target)/web/GetFileByServerRelativeUrl('" + filename + "')/$value?@target='" + hostweburl + "'";//$('#file').attr('href');
        var request = $.ajax({
            url: fileURL,
            type: "GET",
            contentType: "text/plain",

            mimeType: 'text/plain; charset=x-user-defined' // <-[1]
        });

        request.done(function (data) {
            //var filee = "MoveFiles" + count + ".txt";
            zip.file(filee, data, { binary: true }); // <- [2]
            //count++;
            vfilecount++;
            console.log(vfilecount);
            console.log(vfilecount);
         
            if (count == vfilecount) {
                zip.generateAsync({ type: "base64" }).then(function (data) {
                   
                   location.href = "data:application/zip;base64," + data;
                
                });
               
            }
        

        });
    });
}
```

This works fine with Chrome and FireFox  , file downloaded successfully but In IE it generates zip but not download. I must have to use base64 download, because if a file is word and type is blob it generates corrupted zip file. Please provide any solution which supports in IE

**Comment by dduponchel** [comment]
Which version of IE do you need to support ?
IE ≥ 10 means you can use [xhr2](http://caniuse.com/xhr2) (and `responseType = blob`) to fetch data and `saveAs` (+ polyfill) to trigger the "download".
IE ≤ 9 means it will be painful. I never found js-only solutions for that case. You will need VBScript to fetch data ([jszip-utils](https://github.com/Stuk/jszip-utils) wraps that) and flash to trigger the download ([downloadify](https://github.com/dcneiner/downloadify) could help).

**Comment by jimmywarting** [comment]
Worth reading about how to fetch binary data: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data

Bottom line is:
```javascript
xhr.overrideMimeType('text\/plain; charset=x-user-defined');
```

**Comment by dhruvin16** [comment]
I can not use response type=blob
A reason for that is 
File is downloaded successfully but when i open a file it is corrupted format.

**Comment by dhruvin16** [comment]
As Per your Suggestion I changes above code. 
I applied responseType = blob and saveAs(data, "example.zip");  
This works proper in Chrome and Fire Fox but not working in IE. 
In IE it downloads a zip folder but files are not open as original.
When I open .pdf file it opens blank pages. 
When I open .docx file it shows corrupted content.
Wnen I open .jpg or .png file it not opens images.
This issue occurred only in IE . Chrome and Fire Fox work properly.
Please provide any solution 

function create_zip() {
    var zip = new JSZip();
    
    $.each(filePathArray, function (i, path) {

        var filename = path; //"file" + i +".txt";
        var filee = path.substring(path.lastIndexOf('/') + 1);

        var fileURL = appweburl + "/_api/SP.AppContextSite(@target)/web/GetFileByServerRelativeUrl('" + filename + "')/$value?@target='" + hostweburl + "'";//$('#file').attr('href');
        var request = $.ajax({
            url: fileURL,
            type: "GET",
            contentType: "text/plain",

            mimeType: 'text/plain; charset=x-user-defined' // <-[1]
        });

        request.done(function (data) {
        
            zip.file(filee, data, { binary: true }); // <- [2]
                    vfilecount++;
            console.log(vfilecount);
            console.log(vfilecount);
         
            if (count == vfilecount) {
                zip.generateAsync({ type: "blob" }).then(function (data) {// <-- Changed here
                    saveAs(data, "example.zip"); //-- . Applied saveAs insetead of location.href
              
                });
              
            }
          

        });
    });
}

**Comment by dduponchel** [comment]
> I applied responseType = blob and saveAs(data, "example.zip");

I assume you use IE ≥ 10 then. Could you check your page is not loaded in compatibility view ?

> In IE it downloads a zip folder but files are not open as original.

That's strange. Did you use `responseType = "blob"` ? The last snippet your posted uses `$.ajax` and `charset=x-user-defined`. This doesn't work in IE ≥ 10 which only supports the `responseType` on a `XmlHttpRequest` object. See [this comment](https://github.com/Stuk/jszip-utils/blob/v0.0.2/lib/index.js#L44) for more.
As far as I know, `$.ajax` doesn't let you download binary content out of the box (the `x-user-defined` trick is a workaround rather than a real solution). Either use a jQuery plugin (like [jquery.binarytransport.js](https://github.com/henrya/js-jquery/tree/master/BinaryTransport)) or use a xhr directly.

**Comment by dhruvin16** [comment]
I am Using IE 10. File downloads successfully but Word and pdf file are not opened.

**Comment by dhruvin16** [comment]
When I applied above code and applied alert in 
```
request.done(function (data) {
alert(data);
}
```
Here is a result in both browser.

**Chrome Result**
![chrome](https://cloud.githubusercontent.com/assets/23313275/20135601/94067b06-a696-11e6-9ffc-89fe39cbccd1.PNG)

**IE 10 Result**
![ie](https://cloud.githubusercontent.com/assets/23313275/20135600/94063cf4-a696-11e6-8ae7-d1a1a61f7f94.PNG)

Is it mean that $.ajax is not supported by IE to get data?

**Comment by dduponchel** [comment]
> Is it mean that $.ajax is not supported by IE to get data?

Like I said:

> The last snippet your posted uses `$.ajax` and `charset=x-user-defined`. This doesn't work in IE ≥ 10 which only supports the `responseType` on a `XmlHttpRequest` object [to download a binary content].

`$.ajax` is meant to download *text* content, not *binary* content. Same with `XmlHttpRequest` without setting `responseType`. Browsers will try to decode the received content from UTF8 and corrupt it (because it's a binary content, not a text).

Before the XmlHttpRequest level 2 specifications, browsers (all but IE) used the `charset=x-user-defined` hack to get a "binary string". When IE 10 came out, the level 2 specifications where already out and provided a much better way to download binary content: IE 10 implemented directly `responseType` and not the `charset=x-user-defined` hack.

So: don't use `charset=x-user-defined`, use a jQuery plugin (like [jquery.binarytransport.js](https://github.com/henrya/js-jquery/tree/master/BinaryTransport)) or use a xhr directly (with `xhr.responseType = "blob"`).

**Comment by dhruvin16** [comment]
Thank you so much .
This solution works for me.
Add this js to your solution.
https://github.com/henrya/js-jquery/tree/master/BinaryTransport  .

Final Code which works in all browsers which help others.
```
function CreateZip() {
    var zip = new JSZip();

    $.each(filePathArray, function (i, path) {

        var filename = path; 
        var filee = path.substring(path.lastIndexOf('/') + 1);

        var fileURL = appweburl + "/_api/SP.AppContextSite(@target)/web/GetFileByServerRelativeUrl('" + filename + "')/$value?@target='" + hostweburl + "'";//$('#file').attr('href');
        var request = $.ajax({
            url: fileURL,
            type: "GET",
            **dataType: 'binary',**
           
            **processData: false**
        });

        request.done(function (data, status, xhr) {
        
            zip.file(filee, data, { binary: true }); // <- [2]
          
            vfilecount++;
            console.log(vfilecount);
            console.log(vfilecount);

            if (count == vfilecount) {

                zip.generateAsync({ type: "blob" }).then(function (data) {

                    saveAs(data, "example.zip");
                 
                });
              
            }
           
        });
    });

    
}

```
