### ISSUE TITLE
Carriage return trimming

### ISSUE THREAD

**Issue by fibericon** [Stuk/jszip#38]
I was having an issue with the following code:

```
var text_block = '';

text_block += "Variable 1:"+var1+"\r\n";
text_block += "Variable 2:"+var2+"\r\n";
text_block += "Variable 3:"+var3;

var zip = new JSZip();
zip.file("variables.txt", text_block);
```

When I ran this script, it was creating the text file, but there were no new lines/carriage returns when opened in notepad. They showed when opened with wordpad, but I can't assume people are going to use that by default for a .txt file. Turns out, there's this code on lines 661-662:

```
utf8encode : function (string) {
     string = string.replace(/\r\n/g,"\n");
```

Simply commenting out 662 fixed my problem, but I can't imagine any use for it being there at all.

**Comment by badomenspeaking** [comment]
Sorry to return to the subject after so many years, but I'm encountering the same problem zipping text files: CR+NL are always trimmed to CR. The version I use: https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js. 

Enclosed the files before and after.

[R0001.TXT](https://github.com/Stuk/jszip/files/12280151/R0001.TXT)
[R0001.TXT](https://github.com/Stuk/jszip/files/12280158/R0001.TXT).

The code to create the zip:

 zip.file(filename, urlToPromise(url));
 ...  
 zip.generateAsync({type:"blob"}, function updateCallback(metadata) {
...
