### ISSUE TITLE
JSZip not work on macOS Sierra Safari Version 10.0.1 (12602.2.14.0.7)

### ISSUE THREAD

**Issue by nepaul** [Stuk/jszip#380]
JSZip not work on macOS Sierra Safari Version 10.0.1 (12602.2.14.0.7)
Any solution?

**Comment by dduponchel** [comment]
What part does not work ? If it's the download part, it may be linked to https://github.com/eligrey/FileSaver.js/issues/12.

**Comment by nepaul** [comment]
Yes! It's the download part.
