### ISSUE TITLE
Mimetype option doesn't work for docx in nodejs

### ISSUE THREAD

**Issue by edi9999** [Stuk/jszip#383]
Have a look at the following code : 

https://github.com/edi9999/jszip-mimetype-test

Here is what I run : 

```
node bar.js
xdg-mime query filetype output.zip
```

I expect the filetype of output.zip to be "application/zip", however, it is : "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

**Comment by dduponchel** [comment]
The `mimeType` option let you change the [blob's type](https://developer.mozilla.org/en-US/docs/Web/API/Blob/type), that's all. Once written to the disk, you lose this information.

It seems xdg-mime can use `file` which [looks inside the zip file](https://github.com/file/file/blob/master/magic/Magdir/msooxml). In that case, you can't get the `application/zip` mime type without corrupting (or maybe recompressing) the file. You could change the default application for docx files but that's maybe not what you want.
