### ISSUE TITLE
japanese file name encoding are corrupted

### ISSUE THREAD

**Issue by wilfrem** [Stuk/jszip#384]
unzip a zip file and read file names contains japanese characters. but encoding is corrupted.

here is a zip containing the file name.
[jpnfile.zip](https://github.com/Stuk/jszip/files/654150/jpnfile.zip)

this file created at Windows 7. archiver is Windows standard "Send to Compressed (zip) folder"
this file contains jpnfile/新しいテキスト ドキュメント.txt

to reproduce this issue
```
Promise.resolve(zip.loadAsync(data)) // data = the zip file
    .then(function(decodedZip) {
         decodedZip.forEach(function(itemPath) {
              console.log(itemPath); // expect jpnfile/新しいテキスト ドキュメント.txt printed but jpnfile/�V�����e�L�X�g �h�L�������g.txt printed
         });
    });
```

**Comment by wilfrem** [comment]
Thank you. I solve this problem using encoding detection library for byte array at decodeFileName function.

**Comment by QuocTrungLe** [comment]
Can you tell me about line code { var iconv = require('iconv-lite');} ?
Is that the js library? And where i can download it?
