### ISSUE TITLE
Insufficient data for generating image

### ISSUE THREAD

**Issue by swapnilraut1** [Stuk/jszip#392]
HI there,

I am trying to zip pdf file which contains text as well as images generated using jsPDF. When i am opening it, it gives me error "Insufficient data for generating image" & cant see image.
When i am trying same without zipping, it works fine & image is displayed.
Please see code snippet

var zip = new JSZip();
var doc = new jsPDF()

var imgData = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALMAAAAiCAMAAAAj8BgnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAFdQTFRFsVZly46Y+PHyq0hY69TYnis+pDlL8uPlvnJ/3ri+0Zyl2KqxuGRyxYCLs1lozpafrEpa48PIwXeD8eHkpTtM3LS6+PDx1aWt6tLWumh25cbLlx0x////rKqA7wAAA4pJREFUeNrUWNly5CAMFIcvsD2TZJPsYv7/O9cXWBIiyb5sMjxM1QAFLamlFoa4DbdIo4k/c8D+O4qYIe/qQhr2x2BuRcxqX7MTkFkzJdw2GdKdE9kyjcy0xOZrdMwb20a8niHma/TL8/z8cmLuRMjLsC2BFABNLXUn5LxhXZ9wtKQ4+v3mhoRVofUE2udbfs+3p6f56cA8yJhXT9hGXDGaWHo6Pt/YbgHE0Wrl09Gu7dD1v7n+tpoe6uP89ut2f5sPzNkny0iZ08mQDyCXpefu7M1+/YP9pWsJrsjUxgNOzT5tX/0yxxVzPDEDo/DF9mthtVr7Bnty4rnaIK4QnkhxHBnCYyexoqOQV7T32y1hLknECer5BI8+QWBR9TQYiCEpqBllAisHkCHvXIzvz+/x9ue2Yw7U1Gv0RdXDmEmu4mRZOE+ydRM5/giUoucEzHCa8/H1Pt9fj7qBFAXycDjYQcBsuaHEwhZHiIfrGAdjpo4Rcypo1Av1uZeyzCEatmm3RhF3fNWguzXmiaW1Ip3VnNWBYeaM4Tl2YBYVxSIaTgXBR2Rpz+zZYjzg8uDKMGbCBBRN4ElTxiZh1mI1wzTM1FDIdq4oA+aKwjh6qStw2RvAswazowmidg+1XqNh9RdlVqDR/1hRjFDe7aUbI6/zupV6HoL5SlxaiiIuV2cFHnMzUCgK/IOiDKcdgQoLV2uZGhvmmqKEIm8tOkJxT+DsJTXl4qdKQx/hb/c/wNTBU73UEuaaogyFKe4UpD2Ahq6GzxUFBLEqRaUXBJNjtjVFUUwzDmJmu1MvMkT2bIisppSKoittjBMTdigxu6XkLcWc3N/RXZYYOlYVpSkuH+udV4LcN3V2ADIMcMutSz8Do7dHiXO57nNFcRXIy5gJB5jVY4G5rTXPinTLKGqONAyOLm4wSU3xXC9PUvnsnozAGHSjqbIDZEXZ9OtyUDt5N7XCGXuQQSm0CDzrJu4uw9slEJ8UoWj/8/7KG2WUzlpwN0uKx7XUVRXF4TTBMEYJMpmm/SCoegqXiArD+UPG2MizjlXSQMQzlq+VBJmcTaowwAelMvpahvPicQbHsznNnglZl1WsYjZamCfsgM8+JoRVqLYxKR+Q43PxGMajU1Mu/N/vG18dKFzuu7/JfHmEmtD/YMyo1Df2UTAj8TD6UTAjfYKHwYxeEf2jYMbf8PyjYMbfX78F818BBgCbLV7WfgG4yQAAAABJRU5ErkJggg==';
		
doc.addImage(imgData, 'png', 10, 10);

doc.setFontSize(18);
doc.setTextColor(153,0,51);

doc.text('Verification of Employement', 80, 15)
doc.text('Client ID :', leftHeadingX, leftHeadingY);

zip.file("filename.pdf", doc.output());

zip.generateAsync({type:"blob"}).then(function(content) {
	saveAs(content, fileName);
});

**Comment by jimmywarting** [comment]
Try

 var blob = pdf.output("blob");

**Comment by swapnilraut1** [comment]
Thanks Jimmy for quick reply,

Your solution works for me
