### ISSUE TITLE
Unknown object file placed in saved zip file

### ISSUE THREAD

**Issue by granjith** [Stuk/jszip#393]
There is an unknown file called "[object FileList]" is placed inside the saved zip file. Iam using 

    var zip = new JSZip();
    function generateZip(){
        zip.generateAsync({type:"blob"})
            .then(function(content) {
                // see FileSaver.js
                saveAs(content, "test_data.zip");
            });
    }

Is there any thing missing ??

**Comment by dduponchel** [comment]
How do you add files to `zip` ? It looks like you added a `files` object from a `<input type="file">` as a name, not as data. Here is how to do it:

```js
var files = evt.target.files;
for (var i = 0, f; f = files[i]; i++) {
    zip.file(f.name, f);
}
```

**Comment by granjith** [comment]
Thank you dduponchel, i have added your logic its working fine
