### ISSUE TITLE
Can't find end of central directory, html request

### ISSUE THREAD

**Issue by fega** [Stuk/jszip#402]
Hello, I'm triying

```
var html = await request({
    method: 'GET',
    uri: `https://httpbin.org/gzip`,
    encoding: null
  })
var html = await jszip.loadAsync(html)
```
But I'm getting an error. what's wrong?

Thanks

**Comment by dduponchel** [comment]
httpbin.org says:

> `/gzip` Returns gzip-encoded data.

JSZip expect a zip content, not a gzip one. Use [pako](https://github.com/nodeca/pako/) instead:

```js
var pako = require('pako');
pako.inflate(html);
```

**Comment by fega** [comment]
Done, thanks
