### ISSUE TITLE
Is it possible to zip an image file without using getbinarycontent 

### ISSUE THREAD

**Issue by bindukaperla** [Stuk/jszip#405]
```js
var request3 = $.ajax({
    url: URL,
    type: "GET",
    mimeType: "image/jpeg",
    async: false,
});
request3.done(function(data, status, xhr) {
    zip.file(filename[i], data, {
        base64: true
    });
})
```

Am facing issues with base64. Can anyone suggest me what is the issue with my code.

**Comment by dduponchel** [comment]
As far as I know, `$.ajax` doesn't let you download binary content out of the box (it will try to decode your binary from UTF-8 and corrupt it). Either use a jQuery plugin (like [jquery.binarytransport.js](https://github.com/henrya/js-jquery/tree/master/BinaryTransport)) or use a xhr directly (with [`responseType`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType)).

Using jquery.binarytransport.js with your example:

```js
var request3 = $.ajax({
    url: URL,
    type: "GET",
    mimeType: "image/jpeg",
    async: false,
    dataType: 'binary'                       // using jquery.binarytransport.js
});
request3.done(function(data, status, xhr) {
    // Default response type is blob
    zip.file(filename[i], data);
});
```

**Comment by bindukaperla** [comment]
It is workign for image files in this manner by use of XMLHttpRequest()
deferreds.push( addToZip(zip, filename[i], URL) );

function addToZip(zip, imgLink, url){
	var d1 = $.Deferred();
	var xhr = new XMLHttpRequest();
		         xhr.open('GET',url, true);
		         xhr.responseType = "arraybuffer";
		         xhr.onreadystatechange = function(evt) {
		             if (xhr.readyState === 4) {
		                 if (xhr.status === 200) {
		                     zip.file(imgLink, xhr.response);
		                     d1.resolve(zip);
		                 }
		             }
		         };
		         xhr.send();
		         return d1;
}
