### ISSUE TITLE
Zip a txt file, the size is not compressed

### ISSUE THREAD

**Issue by ryanakl** [Stuk/jszip#406]
I tried to zip a text file, but the downloaded zip file doesn't compress the size.

Here is my code:

            var zip1 = new JSZip();
            zip1.file("test.txt", "a very long text here");

            zip1.generateAsync({type:"blob"})
            .then(function(content) {
                saveAs(content, "test.zip");
            });

Could you please tell me what went wrong?

**Comment by dduponchel** [comment]
Use the [`compression`](https://stuk.github.io/jszip/documentation/api_jszip/generate_async.html) option:

```js
zip1.generateAsync({
    type: "blob",
    compression: "DEFLATE"
}).then(...)
```

**Comment by ryanakl** [comment]
Thanks, it works.

**Comment by dduponchel** [comment]
Cool !

**Comment by saivinayabsyz** [comment]
@dduponchel 
It is not working.

**Comment by ewarrenG** [comment]
> @dduponchel It is not working.

+1
