### ISSUE TITLE
Unzipping file results in *.cpgz file in place of contents

### ISSUE THREAD

**Issue by commadelimited** [Stuk/jszip#41]
I'm using Node.js to zip up a directory using the node-zip wrapper for JSZip. The creation of my ZIP file works great, but when I try to unzip the file I get what appears to be another archive instead of the directory I was expecting.

You can check out my entire project here:
https://github.com/commadelimited/jsdownloader

The main work is being done in this file:
https://github.com/commadelimited/JSDownloader/blob/express-version/routes/download.js

But here's the relevant lines of code:

```
writeZip = function(dir,name) {
    var zip = new JSZip(),
        code = zip.folder(dir),
        output = zip.generate(),
        filename = ['jsd-',name,'.zip'].join('');

    fs.writeFileSync(baseDir + filename, output);
    console.log('creating ' + filename);
};
```

The values above are as follows:

```
dir = /tmp/jsd-<randomstring>/
name = <randomstring>
```

Here's the resulting ZIP file:
http://andymatthews.net/uploads/jsd-papuxetada.zip

Could I get some input as to what's going wrong?

**Comment by p1nox** [comment]
I had the same problem. Now I'm using [this](http://stackoverflow.com/questions/18142129/how-to-convert-multiple-files-to-compressed-zip-file-using-node-js/26423629#26423629) and is working.

**Comment by dannydulai** [comment]
the problem is that jszip produces a pkzip file (4.5) and many archival programs only support 2.1
