### ISSUE TITLE
How to just zip files, but not download it yet

### ISSUE THREAD

**Issue by hoa-ho** [Stuk/jszip#415]
Hello,

So I was able to fetch files from multiple urls and zip them together in one folder. However, I don't want to initiate the download yet. The reason is because I want to upload the zip folder into AWS S3.  

So my question is how to just only zip the files and give the zip folder a name without using the saveAs function?

Thanks!

**Comment by dduponchel** [comment]
Once you call `generateAsync`, you get a promise of the zip file content. What you do with it is up to you. You can call `saveAs` and trigger a download or you can upload the content to S3.

From what [I found](https://gist.github.com/joaoffcosta/5729398), you just need to create a `blob` (`zip.generateAsync({type:"blob"})`) and add it to a `FormData` (and send it to S3).
To set the file name, you can: (disclaimer, I didn't test these solutions)
- [transform your Blob to a File](http://stackoverflow.com/a/26181292/1992669) with a name and add the file to the `FormData`
- use [the third parameter of `FormData.append()`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append): `formData.append("file", zipBlob, "your-file.zip");`
