### ISSUE TITLE
Strict Mode support

### ISSUE THREAD

**Issue by jeffkrans** [Stuk/jszip#420]
Hello,

Can you please confirm if JSZip will function properly under strict mode? I'm having trouble getting this library to work in a Salesforce Lightning Component with LockerService enabled.

Thanks!
Jeff

**Comment by puzrin** [comment]
https://github.com/Stuk/jszip/blob/master/lib/compressions.js#L1 look at this in every source file.

**Comment by dduponchel** [comment]
All the code uses the strict mode, that shouldn't cause any issue.

**Comment by KyooMario** [comment]
Hello JeffKrans,

I am running into the same Salesforce LockerService issue. Did you find a fix for this?

Kind regards,
Mario
