### ISSUE TITLE
[ts] Property 'generateNodeStream' does not exist on type 'JSZip'

### ISSUE THREAD

**Issue by TitaneBoy** [Stuk/jszip#423]
Hi there.. Thanks for your great module.

I've downloaded the types for jszip ("@types/jszip": "0.0.32") and unfortunetly, the 'generateNodeStream' does not exists in types file. Is it possible to make an update for it ?

Thanks in advance for your answer.

**Comment by mn4367** [comment]
Had the same problem. I added

````typescript
/**
 * Generate the complete zip file asynchronously.
 * @see generateInternalStream
 * @return a NodeJS ReadableStrem
 */
generateNodeStream(options?: JSZipGeneratorOptions, onUpdate?: (metaData: any) => {}): NodeJS.ReadableStream;
````

to `interface JSZip`in `index.d.ts` and then it worked with the following snippet, taken from some example (forgot where I found it):

````typescript
// Write new Zip file
jszip.generateNodeStream({compression: 'DEFLATE'})
.pipe(FSE.createWriteStream(outFile))
.on('finish', function () {
    // JSZip generates a readable stream with a "end" event,
    // but is piped here in a writable stream which emits a "finish" event.
    console.log(`${outFile} written.`);
});
````

**Comment by KonradCshark** [comment]
There is correct typing for this ;)
