### ISSUE TITLE
Uncaught (in promise) TypeError: external.delay is not a function

### ISSUE THREAD

**Issue by aidanparker** [Stuk/jszip#432]
I’m currently attempting to read the contents of a `.json` file inside a zip. I can get the contents of the zip, but trying to get the actual text from the `.json` gives me an error like:

`Uncaught (in promise) TypeError: external.delay is not a function` or something similar.

I couldn't find anything on this, and I’ve tried pretty much all the examples that were posted. Does anyone know more about this? Pretty new to promises, so any help would be appreciated.

Here is a snippet:
```
var zip = new JSZip();

fs.readFile(filename, function(err, data) {
	if(err) {
		console.error(err);
		return;
	}else {
		console.log(data);
		zip.loadAsync(data).then(function(innerdata) {
			innerdata.file(name + '.json').async('text').then(function success(content) {
				console.info(content);
			}, function error(e) {
				console.error(e);
			});
		});
	}
});
```
Which gives me: `TypeError: external.delay is not a function`

**Comment by aidanparker** [comment]
So, it appears the problem was that I was using the `jszip-sync` branch. Switching to the normal branch fixed this issue.

**Comment by dduponchel** [comment]
Your issue is solved so I will close it.
