### ISSUE TITLE
When creating a blob zip, folder structure is ignored

### ISSUE THREAD

**Issue by htmlgames** [Stuk/jszip#440]
So, if I use base64 and do:
 zip.load(apkBase64, {base64: true}); // apk 'skeleton' webview container
 zip.file("assets/www/autoload.js", "var sb2Data64 = '" + apkData64 + "';")
 var base64 = zip.generate({type:"base64"});
 
the download zip content will overwrite the autoload.js of that currently in the apk (as folder structure matches ok - so standard zip overwrite applies),

However, if I use blob instead:
zip.load(apkBase64, {base64: true}); // apk 'skeleton' webview container
zip.file("assets/www/autoload.js", "var sb2Data64 = '" + apkData64 + "';")
var base64 = zip.generate({type:"blob"});

I get a file in the root : assetswwwautoload.js

and if I append .folder like so

zip.file("autoload.js", "var sb2Data64 = '" + apkData64 + "';").folder("assets"); // overwrite this file in zip with our one!

I get just the autoload.js within the root, and not in the assets folder.

How to get the same behaviour as the base64 please?

**Comment by dduponchel** [comment]
The `generate` options shouldn't change what's in the zip file. Could you check the `zip.files` object ? In both cases you should have the same entries.

**Comment by htmlgames** [comment]
I fixed this a while ago but lost ref to this issue - it was all down to use / (forward slash) rather than \ (backslash) in the path name.
for base64 it didn't matter, but for blobs its does.
You can close this issue.
