### ISSUE TITLE
Generate multiple zip files and then saveAs them in a single, main, zip file.

### ISSUE THREAD

**Issue by iplaksiy** [Stuk/jszip#442]
I think this may have been asked before, but the author of the issue didn't respond, so you ended up closing it. Hopefully, the following explanation might be a little clearer.

I'm trying to generate a handful of zip files (+10), but I really don't want the user to be prompted 10+ times to save them when using the saveAs lib. So, my thought was to generate my collection of zips in memory and then once they're all generated, generate a new, main one, and then use saveAs to allow the user to save it (and all of the ones nested inside of it).

Is that approach possible with the current version of JSZip, and if so, could you please point me in the right direction?

**Comment by iplaksiy** [comment]
Apologies, I figured it out.

For those looking for similar functionality, you will need to do the following:

1. Create a new, main, JSZip instance:
```let mainZip = new JSZip();```

2. Create new, unique, instances of JSZip for each child zip. I used a recursive function:
```
...

//inside loop (haven't tried this) or recursive function
let zip = new JSZip();

...
```
3. Add your content to each unique zip, generate it, and add it to the mainZip instance (MAKE SURE THE FILE NAMES ARE UNIQUE!):
```
...

zip.file('your_file[some_unique_id_here].txt', your_content)
zip.generateAsync({type: 'blob'}).then(content => {
    mainZip.file(your_file[some_unique_id_here].zip, content);
});

...
```

4. When you're done with your loop or recursion, go ahead and generate the main zip and allow the user to save it:
```
mainZip.generateAsync({type: 'blob'}).then(content => {
   saveAs(content, 'main.zip');
});
```

And that should be all.

**Comment by Arunwahatule85** [comment]
Hey @iplaksiy can you help me here 

Below is code in which i am creating data for csv file and downloading csv file in zip folder:

``````````````````
generateCSVfiles()
{

      this.service.getStudentDetails(studentid, student.name).subscribe
          (res => {
            var dataSet = (res);
            // start
            if (studentid == "Senior") {
             
              const header = ["studentId","StudentName"];
              const replacer = (key, values) => values === null ? '' : values // specify how you want to handle null values here
              this.seniordata = items.map(row => header.map(fieldName => JSON.stringify(row[fieldName], replacer)).join(','))
              this.seniordata.unshift(header.join(','));
              this.seniordata = this.seniordata.join('\r\n');
            }
            else if (studentid == "Junior") {
               const header = ["studentId","StudentName"];
              const replacer = (key, values) => values === null ? '' : values // specify how you want to handle null values here
              this.juniordata = items.map(row => header.map(fieldName => JSON.stringify(row[fieldName], replacer)).join(','))
              this.juniordata.unshift(header.join(','));
              this.juniordata = this.juniordata.join('\r\n');
               
            }
        this.downloadzip();
   }
}
   





public downloadzip()
{
	
	 let zip = new JSZip();
      // Fill CSV variable
      zip.file( 'Studentrecord'+'.csv', this.juniordata);
	  zip.file( 'Studentrecord'+'.csv', this.seniordata);
    
    zip.generateAsync({
      type: "base64"
    }).then(function (content) {
      window.location.href = "data:application/zip;base64," + content ;
    });

}
`````````````````````
Above code working fine and able to download csv file inside zip folder when we got response data for one of junior or Senior student . but when we received both junior and senior data at time then it downloading different zip file or sometimes only one zip file getting generated. but i want both file in one zip folder. can someone guide me how to download different csv file in one zip folder.

**Comment by iplaksiy** [comment]
Hey @Arunwahatule85, you should probably wait until both junior and senior data comes in before you run `downloadzip`. 

I'm not entirely sure what `this.service.getStudentDetails()` is doing, but, if it's making multiple XHR requests, perhaps you should use something like [forkJoin](https://www.learnrxjs.io/learn-rxjs/operators/combination/forkjoin) to concat your responses and then pass them to downloadzip as an array instead of assigning them globally?

Then, inside of `downloadzip` you could loop through the array and then run `zip.file()` on each. 

If you provide some more code examples, specifically what `this.service.getStudentDetails()` is doing as well as how/when you're calling `generateCSVfiles()` I could probably provide you with some further direction.

**Comment by Arunwahatule85** [comment]
Hello @iplaksiy  I have updated my code...how i can wait until both junior and senior data come

**Comment by iplaksiy** [comment]
So, the issue here is that your iteration does not wait for the each observable to complete before moving on to the next one.

I usually use Promises for something like this, so below is an example of that, however, I'm sure there's an RXJS way to solve this as well, so you may want to explore that.

Take a look at [Bluebird](http://bluebirdjs.com/docs/getting-started.html) for iterating async in series.

```
import * as Bluebird from 'bluebird';

...

//first iterate through everything in series
await Bluebird.each(this.studentdata, (data) => {
    return new Promise((resolve, reject) => {
        this.service.getStudentDetails(student.studentId, student.StudentName).subscribe(res => {
             ...
             //once you finish your conditionals
             resolve();
        })
    });
});

//then, once complete, run download zip
this.downloadzip();

```

**Comment by Arunwahatule85** [comment]
Thanks @iplaksiy  you saved my time..Amazing answer you have provided ...Really Thanks !
