### ISSUE TITLE
Generating a .zip file with a .docx inside it does not work

### ISSUE THREAD

**Issue by gpalomar** [Stuk/jszip#447]
Hi! Comming from #403 

My purpose is to generate a .zip file with the following structure: (directory) --> (file)

When "file" is of format .txt works as expected, but when file is of format .docx, it doesn't work. When I decompress the downloaded zip, I see a file called DOCS.zip.cpgz instead of DOCS.zip.

My code looks like this:

```javascript
var reader = new FileReader();
reader.onload = function() {

    // --------------------------------------------- DOES NOT WORK
    // Code for the .docx test
    var zip = new JSZip();
    zip.folder('DOCS/');
    zip.file('DOCS/document.docx', file, {binary: true});
    
    var blob = zip.generateAsync({ type: 'blob' });
    FileSaver.saveAs(blob, 'DOCS.zip');
    // I use FileSaver to download the generated .zip file.

    // --------------------------------------------- WORKS FINE
    // Code for the .txt test
    var zip = new JSZip();
    zip.folder('DOCS/');
    zip.file('DOCS/document.txt', file, {binary: true});
    
    var blob = zip.generateAsync({ type: 'blob' });
    FileSaver.saveAs(blob, 'DOCS.zip');
};
// file variable is retrieved from an input type file
reader.readAsArrayBuffer(file);
```

@dduponchel I don't know how to explain it better. Hope it's 
understandable...

**Comment by dduponchel** [comment]
`generateAsync({type:"blob"})` doesn't return a blob, it returns a **promise** of blob.

Instead of
```js
var blob = zip.generateAsync({ type: 'blob' });
FileSaver.saveAs(blob, 'DOCS.zip');
```
Use:
```js
zip.generateAsync({ type: 'blob' }).then(function (blob) {
  FileSaver.saveAs(blob, 'DOCS.zip');
}).catch(function (e) {
  console.error("an error occured", e);
});
```

The first version don't work on my side (tested in Firefox and Chrome), I get an error:

> TypeError: Argument 1 is not valid for any of the 1-argument overloads of URL.createObjectURL.

I don't know why you got the text version to work, it should have failed too !
Also, you don't need the `FileReader`, JSZip can read blobs.

**Comment by gpalomar** [comment]
Sorry @dduponchel , this is not exactly my code. My code supports the promise return. It was only an example trying to explain that it is not possible to download a generated zip file containing a docx file. That's because code fails when you try it.
In my original code, files are decrypted in client side and later I generate a ZIP using the decrypted  blob. Only .docx files don't work when attaching them into a the generated ZIP.

**Comment by dduponchel** [comment]
I will need the code (or at least the snippet) manipulating the data given to / taken from JSZip. With the correct input, you should be able to add any type of files.

**Comment by gpalomar** [comment]
Hi again! 
I have made a fiddle using that situation: https://jsfiddle.net/7egb7v8h/

Adding screenshots of the different results (.txt vs .docx). Tested in 2.x and 3.x versions and same result 😞 

My output using a .txt file.
![with_txt](https://user-images.githubusercontent.com/3463553/29580172-65cf39ce-8775-11e7-9c64-0a61012f69f5.png)

My output using a .docx file.
![with_docx](https://user-images.githubusercontent.com/3463553/29580161-6193a89a-8775-11e7-83a3-f3f9a160afe2.png)

Hope this helps to check what I do wrong or what is failing in library.

**Comment by dduponchel** [comment]
On my side (linux) I get a correct result:
```
$ zipinfo DOCS.zip 
Archive:  DOCS.zip
Zip file size: 4318 bytes, number of entries: 2
drwx---     2.0 fat        0 b- stor 17-Aug-22 18:23 DOCS/
-rw----     2.0 fat     4106 b- stor 17-Aug-22 18:23 DOCS/plop.docx
2 files, 4106 bytes uncompressed, 4106 bytes compressed:  0.0%
```

```
$ unzip -t DOCS.zip
Archive:  DOCS.zip
    testing: DOCS/                    OK
    testing: DOCS/plop.docx           OK
No errors detected in compressed data of DOCS.zip.
```

I know Finder on mac handles really poorly zip files and generates `.cpgz` files instead of saying what's wrong. 
Could you add here the generated `DOCS.zip` ?

**Comment by gpalomar** [comment]
Input: [test.docx](https://github.com/Stuk/jszip/files/1243010/test.docx)
Output: [DOCS.zip](https://github.com/Stuk/jszip/files/1243012/DOCS.zip)

**Comment by dduponchel** [comment]
Thanks. I don't see anything wrong here (I can open it without issue on my side). I'll see if I can use the mac of a coworker tomorrow to test different configurations.

Meanwhile, could you test with `zip.generateAsync({type: 'blob', platform: 'UNIX'})` ?

**Comment by gpalomar** [comment]
Sorry @dduponchel , but same thing... I'll wait your coworker test a we'll see if he has the same result or not.

**Comment by dduponchel** [comment]
I reproduced the issue on his Mac. Strangely, I don't get the issue without the folder. I may have more time in the following days to investigate and (try to) find out which combination Finder doesn't like.

**Comment by gpalomar** [comment]
Yes, this was what I thought... it's a strange situation. Hope you find a solution. Thanks for your attention!

**Comment by dduponchel** [comment]
I may have a "solution". But first a rant, because I need to get that out of my chest !

- In every cases, the `unzip` utility works and extract generated zip files.
- `open -a "Archive Utility" DOCS.zip` is the closest to command line I could find but I still get a zero as return code and no output
- having `DOCS/` then `DOCS/test.docx` doesn't work
- having `DOCS/test.docx` works
- having `DOCS/test.docx` **then** `DOCS/` works (!)
- having `DOCS/` then `DOCS/test.docx` where the content is actually a text works (!!)

When I activated the compression, everything magically worked:
```js
zip.generateAsync({
  type: "blob",
  compression: "DEFLATE" // <-- HERE
})
```
It works with `platform: "UNIX"` and `platform: "DOS"` too.

Which also means: I can generate a zip with mac's `zip` that can't be opened by mac's Finder:
```
zip -r0 DOCS.zip DOCS/
```
`-r` for recursively zip the folder, `-0` to disable compression. The generated zip file has the same issue.

So:
- use `compression: "DEFLATE"`
- don't use Finder to extract zip files, it's actually worse than Windows' Compressed Folders

Could you confirm the "fix" ?

**Comment by gpalomar** [comment]
With the compression: "DEFLATE" works perfectly opening with Finder. Thanks @dduponchel for your help! Closing issue.

**Comment by dinshawraje** [comment]
Hi I am facing same issue I had tried below code.
`function DownloadZip() {
    const zip = new JSZip();
    zip.file("insert1/smile.gif", "R0lGODdhBQAFAIACAAAAAP/eACwAAAAABQAFAAACCIwPkWerClIBADs=", { base64: true });

    zip.file("DOCS/test.docx", "aGVsbG8gd29ybGQK", { base64: true });

    zip.generateAsync({ type: 'blob', compression: "DEFLATE"  }).then(function (blob) {
        saveAs(blob, 'DOCS.zip');
    }).catch(function (e) {
        console.error("an error occured", e);
    });    
}`
.docx file gives error that file is corrupted.

**Comment by yfram** [comment]
Hi, any progress? having the same issue
