### ISSUE TITLE
version upgrade 3.1.4

### ISSUE THREAD

**Issue by hassanalami** [Stuk/jszip#453]
Version should be upgraded to 3.1.4

https://github.com/Stuk/jszip/blob/185c545c39d00fe056b3f3b388bab1bda954379d/dist/jszip.min.js#L3

https://github.com/Stuk/jszip/blob/185c545c39d00fe056b3f3b388bab1bda954379d/dist/jszip.js#L3

**Comment by dduponchel** [comment]
Good catch!
The generated files are ok and contain the latest fixes, but the version number is wrong.
I'll re-release them.

**Comment by dduponchel** [comment]
The version 3.1.5 [is out](https://github.com/Stuk/jszip/blob/v3.1.5/dist/jszip.js#L3).
