### ISSUE TITLE
ReferenceError: JSZipUtils is not defined

### ISSUE THREAD

**Issue by etshy** [Stuk/jszip#454]
Hi
I got the following problem after installing jszip via npm and copy/past (literraly) the "mini app : downloader"
ReferenceError: JSZipUtils is not defined
the error message is shown in the error callback of urlToPromise method (from the mini app code).

why jszipUtils is not installed automatically via npm ? 
Checked the package.json from jsutils (in the folder I installed) there is nothing about jszipUtils
and there is no documentation on jsziputils so don't know what to do to correctly install it.

Thanks in advance.

**Comment by dduponchel** [comment]
[JSZipUtils](https://stuk.github.io/jszip-utils/) is not a dependency of JSZip so it won't be installed automatically.
You can install it with `npm i jszip-utils`.

**Comment by etshy** [comment]
yeah I installed it , but thought it was a dependency and there was a problem.

OK so no problem here, Thanks.
