### ISSUE TITLE
Wrong version number of v3.1.4?

### ISSUE THREAD

**Issue by danny0838** [Stuk/jszip#478]
According to the documentation the latest version is 3.1.4. However, the js files in the dist/ directory of the downloaded zipball says 3.1.3:

    /*!

    JSZip v3.1.3 - A Javascript class for generating and reading zip files
    <http://stuartk.com/jszip>

    (c) 2009-2016 Stuart Knightley <stuart [at] stuartk.com>
    Dual licenced under the MIT license or GPLv3. See https://raw.github.com/Stuk/jszip/master/LICENSE.markdown.

    JSZip uses the library pako released under the MIT license :
    https://github.com/nodeca/pako/blob/master/LICENSE
    */

**Comment by dduponchel** [comment]
That's the issue #453. Only the version number is wrong, I'll try to release the version 3.1.5 soon (which will re-generate the files).

**Comment by danny0838** [comment]
OK. Thank you, and sorry for missing #453.
