### ISSUE TITLE
The minified script is building corrupt files

### ISSUE THREAD

**Issue by adam-winfree** [Stuk/jszip#483]
I'm sure I'm doing something incorrectly because no one else seems to be having this issue, but the minified script builds corrupt files (the script that hasn't been minified works fine). I believe it is because the Unicode characters are being converted from their literals to Unicode. For example:

`exports.LOCAL_FILE_HEADER = "PK\x03\x04"`

Becomes this when minified:

`c.LOCAL_FILE_HEADER="PK",`

When it uses that data to write, it seems to be writing the unicode characters, and not the hex. My app should be reading everything as UTF-8, so it should be able to process the script correctly. I'm not sure where the issue is. Is there something missing in the documentation (or something I'm not seeing)?

Thanks!

**Comment by dduponchel** [comment]
Where do you see this `LOCAL_FILE_HEADER="PK"` ? The `\x03` is a control char in ascii/utf8 which isn't meant to be displayed. In my terminal it isn't displayed, in my browser in the textarea it is displayed as a small box [00/03] and in the markdown render I see [replacement characters �](http://www.fileformat.info/info/unicode/char/fffd/index.htm).

If you use UTF-8 everywhere, you shouldn't have any issue (setting `ASCIIOnly: true` in our uglifyjs configuration would be extra safe).

> When it uses that data to write, it seems to be writing the unicode characters, and not the hex.

Do you get a corrupted zip file ? Could you share a snippet showing your code using JSZip ?

**Comment by adam-winfree** [comment]
I copied the text from the minified file in here. It pasted with the replacement characters, but I see spaces in my IDE (for some of them).
https://github.com/Stuk/jszip/blob/master/dist/jszip.min.js

I thought about running uglify with that option, but wasn't sure if you threw on any extra options when you minify this puppy.

I'm using the [DataTables](https://datatables.net/download/index) plugin for jQuery (version 1.10.9 using version 2.5 of JSZip). Long story short, the JSZip plugin is used to create an Excel file. The generated Excel file looks/works fine with the file that isn't minified. I thought my IDE may have been doing something funky when I looked at it, so I just downloaded the file and moved in in command line to the proper place in my project.

This isn't super helpful, but when I cat the files, here are the first couple of lines of the broken Excel file:
```
PK  
EMiK_rels/PK  
EMiKxl/PK  
EMiK	xl/_rels/PK  
EMiKxl/worksheets/PK  
```

And from the working one:
```
PK
?rhK_rels/PK
?rhKxl/PK
?rhK	xl/_rels/PK
?rhKxl/worksheets/PK
```

**Comment by dduponchel** [comment]
> I thought about running uglify with that option, but wasn't sure if you threw on any extra options when you minify this puppy.

[Our uglifyjs options](https://github.com/Stuk/jszip/blob/v3.1.5/Gruntfile.js#L151) are mainly there to get the correct banner in the minified version.

I'll add the `ASCIIOnly` option. Could you confirm that [this file](https://github.com/dduponchel/jszip/blob/issue483_dist/dist/jszip.min.js) works as expected ?

**Comment by adam-winfree** [comment]
I don't think this is an issue with this package. I think the other package, but it is difficult to determine. I appreciate your time and help. Sorry for wasting it.

**Comment by Worthy7** [comment]
@adam-winfree After 2 days, I have finally discovered this is the issue for my broken excel files.
(The problem is that datatables-formatting which is included in excels xl/styles.xml is not encoded properly which fudges everything) and this has something to do with jszip not properly encoding that formatting, only when we gulp's uglify.

Did you find a solution to this? It looks like I'll have to just separate jszip into it's own script away from the main bundle....

**Comment by Worthy7** [comment]
@dduponchel (ascii_only made no difference)

**Comment by adam-winfree** [comment]
@Worthy7 Looking back at my commits on the project, I think we just dropped support for Excel on the project I was working on. Sorry.
