### ISSUE TITLE
jszip+request zip many remote server file fail

### ISSUE THREAD

**Issue by jiangli373** [Stuk/jszip#499]
I have two files save in remote server, i want to download them into local zip file; I test sometimes only one file can download complete, other only can download parts data, the reason i guess is when 

> zip.file('name1.dmg', stream1);

> zip.file('name2.dmg', stream2);

jszip process one file in parallel, other file stream is paused; when first is done, second file will  resume; if first file send time more than 2 mins, remote server will close connection , so second file can't download complete.

I used [request](https://github.com/request/request) 

For example
```
'use strict';
const JSZip = require('jszip');
const request = require('request');
const fs = require('fs');
const path = require('path');
const sss = path.join(__dirname, 'me.zip');

const resultArr = [
  {
    fileName: 'charles-proxy-4.1.4.dmg',
    downLoadUrl: 'http://p2oryw9jc.bkt.clouddn.com/charles-proxy-4.1.4.dmg'
  },
  {
    fileName: 'googlechrome_mac_59.0.3071.109.dmg',
    downLoadUrl: 'http://p2oryw9jc.bkt.clouddn.com/googlechrome_mac_59.0.3071.109.dmg'
  }
];
const zip = new JSZip();
resultArr.map(item => {
  let inStream = request.get(item.downLoadUrl);
  let name = item.fileName;
  const inPaht = path.join(__dirname, item.fileName);
  let length = 0;
  inStream
    .on('response', function (response) {
      console.error(name + '--content-type--', response.headers); // 'image/png'
    })
    .on('data', function (data) {
      length += data.length;
    })
    .on('error', function (e) {
      console.error(name + '---error---->', e);
    })
    .on('end', function () {
      console.error(name + '---end---- length:'+ length);
    });
  zip.file(item.fileName, inStream);
});
const stream = zip.generateNodeStream({type: 'nodebuffer', streamFiles: true});
stream.pipe(fs.createWriteStream(sss));
stream
  .on('data', function (data, metadata) {
  })
  .on('error', function (e) {
    console.error('---error-----', e);
  })
  .on('end', function () {
    console.error('---end-----');
  });

```
Is there any way to solve this problem? 

Thank you!

**Comment by colbygk** [comment]
This sounds like an issue that is not specific to the functioning of jszip itself, but of your environment. You should look for environment settings for your application that relate to the timing out of connections. In anycase, this does not appear to be an issue specifically related to jszip

**Comment by jiangli373** [comment]
Thank you for your reply! I closed this issue
