### ISSUE TITLE
UNZIP Object error in IE9

### ISSUE THREAD

**Issue by kleysonr** [Stuk/jszip#50]
I have the following piece of code:

```
$.ajax({
    url: "file.zip",
    beforeSend: function ( xhr ) {
        xhr.overrideMimeType("text/plain; charset=x-user-defined");
    }
})

.done(function ( data ) {
    var zip = new JSZip(data);
    ( ... )
});
```

The code work very well in Firefox and Chrome, but in IE9 at 'new JSZip(data)' I get the error:

End of stream reached (stream length = 251617, asked index = 251619). Corrupted zip ? 

Kleyson Rios.

**Comment by prabhuthil** [comment]
kleysonr  what is the solution your friend suggested to you in IE 9?

**Comment by kleysonr** [comment]
Sorry, I dont remember.

Also I dont remember where it was used to check :(
