### ISSUE TITLE
Upload Image,convert it to zip( client side ) and then upload to server

### ISSUE THREAD

**Issue by PAVANKUSHVAHA** [Stuk/jszip#501]
hey guys,
**Need**
 Upload image file,and convert it to zip on client side and then upload ( converted zip ) file to server.
I have done this,
`<input type="file"  name="plan[]" onchange=" zipFile(event);" multiple>`
`<input type="file"  name="plan_zipped" id="test">`
`function zipFile(evt){`
		`  var zip = new JSZip();`     
                ` var files = evt.target.files;`
		` for (var i = 0; i < files.length; i++) {`
		    ` var f = files[i];`
		   `  zip.file(f.name, f);`
		` }`

`var sss = document.getElementById('test');`
		` sss.files = zip;'
`}`

and there is error,i have no clue :(
any solution here,
Thanks !

**Comment by colbygk** [comment]
This seems like a more appropriate question for stackoverflow: https://stackoverflow.com/questions/tagged/jszip

**Comment by PAVANKUSHVAHA** [comment]
@colbygk 
yes, i have fixed this issue,
here is answer [https://stackoverflow.com/a/48903478/7294656](url)
