### ISSUE TITLE
How can I use jszip with Expo (React Native) ?

### ISSUE THREAD

**Issue by bertbeck** [Stuk/jszip#521]
I get "unable to resolve module 'stream' when I try to use jszip in an Expo app.Expo is a javascript only version of React Native.

**Comment by eXXeption** [comment]
I am getting this too:
```
ERROR in ./node_modules/jszip/lib/readable-stream-browser.js
Module not found: Error: Can't resolve 'stream'
```
I don't think it's related to a specific ui/js framework, as I am using angular6/devextreme while getting this error.

I expect it to be a problem with webpack 4 bundling maybe, as the error occures after upgrading from angular5 to angular6 which is using webpack 4.

**Comment by beeing** [comment]
Yes, having the same issue when building for angular6

**Comment by eXXeption** [comment]
@beeing 
You can fix the angular build by adding node_modules/jszip/dist/jszip.min.js to the tsconfig -> compilerOptions -> paths

**Comment by annelorraineuy** [comment]
Has anyone figured out how to use jszip with react-native?

**Comment by annelorraineuy** [comment]
I fixed this error by installing the unresolved module. In my case it was stream. So `npm i stream --save` and then clearing cache and restarting watchman fixed the issue.

**Comment by antoineblueberry** [comment]
npm install --save jszip stream
import * as JSZip from 'jszip';
