### ISSUE TITLE
Any complaints about using default extractor in windows and missing files?

### ISSUE THREAD

**Issue by csteez** [Stuk/jszip#535]
Hi! 
First off, I'd like to say thank you for making such a nice tidy little utility library. It is really useful!
I'm using it to generate a set of folders with files. It works great on macOs, everything is as anticipated. Also works well with Windows + 7Zip. 
I tried to unzip on windows with the default extractor and found that most of the folders are missing. I'm not sure where in my process the issue originated; I was wondering if anyone else had run into this or had suggestions. I'm using a blob type as in the example for downloading the files with FileSaver - not sure if this is part of the problem actually. 

I tried using a data-url, and that works fine so it's not the folder itself.  Unfortunately that doesn't work in IE :( 

Just wondering if anyone's run into this or has any suggestions :)

**Comment by csteez** [comment]
Somehow updating the file order fixed everything.

**Comment by offaxis** [comment]
Hi @csteez  !

Can you provide a sample of how you solved it please ?

**Comment by csteez** [comment]
I wish I could help, I don't have access to the code anymore, otherwise I'd let you know. I think something around what order i zip'd the files in. Good luck!

**Comment by offaxis** [comment]
Hi,
keeping having this problem as described by @csteez : the archive seems to be well filled in mac and on windows (unarchived with 7zip), but with default windows extractor, there is no subfolder, but files in root ('/') are present...

any clue ?

**Comment by mnjdev** [comment]
Hey,
I think the issue still exists, my application accepts zip file from users so there is no way to check if the users are sending the zip file which was compressed using native compression software of windows and it is not acceptable to advice users how to compress their files. If anybody here know any solution around it, please let me know.

@csteez If possible, can you re open this issue?
