### ISSUE TITLE
Check if ZIP has password?

### ISSUE THREAD

**Issue by IdkGoodName** [Stuk/jszip#547]
I want to check if ZIP has password & Get the password.
I am making Zip Manager app, and i want that users would type password if zip has one.

**Comment by username1565** [comment]
Look in the source code of [minizip-asm.min.js](https://github.com/username1565/minizip-asm.js/blob/master/lib/minizip-asm.min.js) to add ability working with password.

**Comment by gildas-lormeau** [comment]
@IdkGoodName You could be interested in using zip.js (https://gildas-lormeau.github.io/zip.js/). It supports AES anf ZipCrypto encryption.
