### ISSUE TITLE
Setting dosPermissions creates folder instead of file

### ISSUE THREAD

**Issue by ffflorian** [Stuk/jszip#550]
Hi,
when adding a file to a JSZip object and setting `dosPermissions` in the configuration, a folder instead of a file is created.

Sample code:
```js
const JSZip = require('jszip');
const zip = new JSZip();

const fileContent = 'Hello, World!';

zip.file('test.txt', fileContent);
zip.file('test2.txt', fileContent, {unixPermissions: 33206});
zip.file('test3.txt', fileContent, {dosPermissions: 33206});

console.log(`zip.file('test.txt') exists:`, !!zip.file('test.txt')); // true
console.log(`zip.file('test2.txt') exists:`, !!zip.file('test2.txt')); // true
console.log(`zip.file('test3.txt') exists:`, !!zip.file('test3.txt')); // false

console.log(`zip.folder('test3.txt') exists:`, !!zip.folder('test3.txt')); // true
```

[Demo on JSFiddle](https://jsfiddle.net/kf0pL4vg/)

**Comment by ffflorian** [comment]
@Stuk any update on this?

**Comment by v1nce** [comment]
dosPermissions  <> unixPermissions
dosPermissions should've be named dosAttributes instead.

The meaning of bits for dosPermissions is

Bit 0: read only. 
Bit 1: hidden.
Bit 2: system file. 
Bit 3: volume label.
Bit 4: (sub)directory.
Bit 5: archive

As you set the bit 4 the file became a folder

**Comment by ffflorian** [comment]
@v1nce 

Oh wow, I didn't event think of that! Thank you :slightly_smiling_face:
