### ISSUE TITLE
Error: Ajax error for filepath : 404 Not Found

### ISSUE THREAD

**Issue by olemalik** [Stuk/jszip#608]
H! 
when i deploy and try to download then its say file not found
Error: Ajax error for /Areas/Client/UploadedFiles/2327/Driveshaft.dwg : 404 Not Found

Failed to load resource: the server responded with a status of 404 (Not Found)

when i upload jpq or pdf its works fine but .dwg  file giving error

```
function zipFiles(file_paths, zipFileName, id) {
    var zip = new JSZip();
    var count = 0;   
    file_paths.forEach(function (url) {
        JSZipUtils.getBinaryContent(url, function (err, data) {
            if (err) {
                //throw err;
                showNotification(err);
            }
            count++;
            if (data != null) {
                zip.file(url, data, { binary: true });
             
                if (count == file_paths.length) {
                    debugger
                    zip.folder('' + uploadedDirectory+'' + id+'/')
                        .generateAsync({ type: 'blob' }).then(function (content) {
                            debugger

                            saveAs(content, zipFileName);
                        });
                }
            }
        });
    });
}```

**Comment by maximerety** [comment]
Hi @olemalik, it seems you're having an issue with `getBinaryContent` from https://github.com/Stuk/jszip-utils.

Would you mind closing this issue and opening another issue there (https://github.com/Stuk/jszip-utils/issues) if your problem is persisting?

Best regards,

**Comment by olemalik** [comment]
I have close this issue and opened a new issue here : [Error: Ajax error for filepath : 404 Not Found](https://github.com/Stuk/jszip-utils/issues/26)
