### ISSUE TITLE
Is there a way to load files into the Zip from remote URL?

### ISSUE THREAD

**Issue by diegovdev** [Stuk/jszip#61]
Is there some way to load the files into the Zip from given URLs?? For example something like this:

```
var zip = new JSZip();
zip.file("Hello.txt", "http://mywebsite.com/files/Hello.txt");
```

**Comment by vipera7** [comment]
Can we get an example usage?

**Comment by sapeish** [comment]
[Here](https://github.com/sapeish/moodle-save-all-resources/blob/master/moodle-save-all-resources.user.js#L137) is a sample of how I used the [fileURL](https://github.com/sapeish/jszip/blob/load-from-url/jszip.js#L587) method I implemented.

**Comment by akanshayadav11** [comment]
Hey,
Great article! 

I want to do a comment if you allow me.
Please check below link:
https://dipoletechi.com/blog-post/how-to-download-zip-from-http-url-and-unzip-using-react-node/


Thanks
