### ISSUE TITLE
[base64 data] ERROR:  Can’t read the data of ‘file.jpg’. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?

### ISSUE THREAD

**Issue by leonardofmed** [Stuk/jszip#615]
I'm getting this error when I try to add a base64 string to a zip file with the function: `zip.file(image.name, base64String, {base64: true});`

I'm using an Ionic app (v4) and it was working fine, the error is just with base64 images. I have a function that reads the image asynchronously and return the base64 string to the function above.

My 'get image' function:
```
async uriToBase64(uri) {
	console.log('File received to be converted: ', uri);
        // Just remove the file path and get the name
	let nameFile = uri.replace(this.file.dataDirectory, '');
	console.log("File name to be converted: ", nameFile);

	await this.file.readAsDataURL(this.file.dataDirectory, nameFile).then((file64) => {
                // Remove initial extension from the string
		let fileWithoutExtension = ('' + file64 + '').replace(/^data:image\/(png|jpg|jpeg);base64,/, '');
		console.log("File without extension: ", fileWithoutExtension);
		return fileWithoutExtension;
	})
	.catch(err => {
		console.log("Error while transforming image to base64: ", err);
	});		
}
```
I can see in console all the outputs, so I think everything is working fine. From the console I get the base64 string and decoded it, which returned my image, so I think this is ok too. I can't understand why it isn't accepting my base64 string.

**Comment by maximerety** [comment]
My 2 cents, if it may help... `uriToBase64` does not seem to return anything.

Are you using this function to set the value of `base64String`? Something like this:
```js
const base64String = await uriToBase64(uri);
zip.file(image.name, base64String, {base64: true});
```

You might want to slightly change `uriToBase64`:
```diff
 async uriToBase64(uri) {
     // [...]
-    await this.file.readAsDataURL(this.file.dataDirectory, nameFile).then((file64) => {
+    return this.file.readAsDataURL(this.file.dataDirectory, nameFile).then((file64) => {
         // [...]
         return fileWithoutExtension;
     })
     .catch(err => {
         console.log("Error while transforming image to base64: ", err);
     });
 }
```

**Comment by leonardofmed** [comment]
@maximerety , thank you very much for your help. With the help of one of the Ionic Forum's moderators I was able to fix this problem. [Here ](https://forum.ionicframework.com/t/ionic-4-doubt-regarding-an-asynchronous-function-and-how-i-should-correctly-run-it-synchronously/172371/17?u=leonardofmed) is the link if you want to see the details. Indeed, the problem of this function was the missing returning value!
