### ISSUE TITLE
jszip async doesn't work in edge browser

### ISSUE THREAD

**Issue by charmjeh** [Stuk/jszip#645]
### Summery

in edge browser, i got error "ZipObject.prototype.async (eval code:75:9) at Anonymous function".
What can I do?

### Detail

some of my user MUSE USE  **Microsoft Edge browser** and i am using **44.18362.449.0 version**
but  when i used async, it returns this error

```
Unhandled promise rejection TypeError: The call object is invalid.
[object Error]: {description: "The call object is invalid..", 
message: "The call object is invalid.", 
number: -2147418113, 
stack: "TypeError: The call object is invalid. at exports.delay (eval code:380:5) 
at StreamHelper.prototype.resume (eval code:179:9) 
at Anonymous function (eval code:83:9) at Promise (eval code:177:7) 
at accumulate (eval code:78:5) at StreamHelper.prototype.accumulate (eval code:152:9)
 at ZipObject.prototype.async (eval code:75:9) at Anonymous function (eval code:404:15) 
at out.forEach (eval code:189:17) at Anonymous function (eval code:403:13)"}
```

My code is below, and in chrome it works as I want.
```
          let zip = new JSZip();
          var cnt = 0;
          zip.loadAsync(obj.data).then(zipData => {
            zipData.forEach((relativePath, zipEntry) => {
              zipEntry.async("arraybuffer").then(content => {
                  // There seems to be an error here.
              }
```

** printed value example (console.log) **
[ relative value ]
22.jpg

[zipEntry]
_data: Object
_dataBinary: true
comment: null

date: [date] Thu Jan 02 2020 13:54:50 GMT+0900 (대한민국 표준시)
dir: false
dosPermissions: null
name: "22.jpg"

options: Object
unixPermissions: 33188

__proto__: Object

**Comment by imblowsnow** [comment]
me too
