### ISSUE TITLE
JSZip returning a .file

### ISSUE THREAD

**Issue by jefftaglic** [Stuk/jszip#655]
My coworkers and I are using JSZip to send zipped bundles of images over browser, and we ran into a bit of an issue. We are using the following code:

`
if (count == urls.length) {
  zip.generateAsync({type:'blob'}).then(function(content) {
    saveAs(content, name);
  });
}
`

On Firefox, IE and Edge, it delivers a zip file to the user, while on Chromium-based browsers (tested on Chrome and Brave) it simply delivers a corrupt download.file

Please let me know if this is a known issue, or any potential ways to circumvent this.

https://stackoverflow.com/questions/60625411/jszip-not-working-properly-on-firefox-and-complete-not-working-in-chrome

**Comment by pascalhollmann** [comment]
We noticed the same Error. With a Version of 2014 (We copied from the Example https://stuk.github.io/jszip/documentation/examples/download-zip-file.html) it worked.

**Comment by Stuk** [comment]
Looks like this is answered?

**Comment by pascalhollmann** [comment]
> Looks like this is answered?

I think it is only a workaround. The issue is not solved.
