### ISSUE TITLE
Empty zip archive

### ISSUE THREAD

**Issue by ibnyusuf** [Stuk/jszip#660]
I am attempting to upload a folder by recursively adding the files and subfolders to a zip and then uploading the zip using AJAX. Below is the code that I have written:

```
if(item.isDirectory){
    var zip = new JSZip();
    create_zip_dir(zip, item, "");

    zip.generateAsync({
      type: "blob"
    }).then(function (file) {
      console.log(file);
      file = new File([file], item.name + ".zip", {
        type: "application/zip"
      })
      console.log(file);
      //console.log(file); 
      do_upload(file, wd_id);
    });

function create_zip_dir(zip, item, path){

  if(item.isFile){
    var name = path + item.name;  
    item.file(function(file) {
      if(file.name.substring(file.name.lastIndexOf('.')+1) === "docx"){
        file = new File([file], file.name, {
          type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        })
      }
      zip.file(name, file);
    });
  } else if(item.isDirectory){
    var dirReader = item.createReader();
    dirReader.readEntries(function(entries) {
      for (var i=0; i<entries.length; i++) {
        create_zip_dir(zip, entries[i], path +  item.name + "/");
      }
    });
  }
}
```

However, no matter what the contents of the folder that I am attempting to zip, the blob that is created always has size 22 bytes. The console.log our that I see is:

```
Blob {size: 22, type: "application/zip"}
size: 22
type: "application/zip"
__proto__: Blob
```

When I check the .zip after upload, the archive is invariably empty. Any help appreciated.

**Comment by jhwaters** [comment]
I think the problem is probably that `item.file(...)` is asynchronous, so the file hasn't actually been added by the time you call `zip.generateAsync`. Try adding `console.log('file added!')` after `zip.file(name, file)` and see if it gets printed before or after the blob. The solution, if this is the issue, is to wrap the `item.file(...)` in a promise that resolves to the file to be added, and give that promise to JSZip.

**Comment by Stuk** [comment]
I'm afraid I don't have time to answer questions here. Please ask on StackOverflow with the [jszip tag](https://stackoverflow.com/questions/tagged/jszip). Thank you!

**Comment by salivity** [comment]
i used a setInterval the promise structure did'nt work
