### ISSUE TITLE
Changelog needs to be updated

### ISSUE THREAD

**Issue by yabejarano10** [Stuk/jszip#662]
the changelog found in https://stuk.github.io/jszip/CHANGES.html is out of date since Version 3.1.5. 
I would like to know if the recent versión 3.3 fix the performance issues found in 3.2.x reported here: https://github.com/Stuk/jszip/issues/617 

I'm using version 3.1.5 because of this but with the most recent release I'd like to know if is better to use 3.3 instead of 3.1.5 in terms of performance, specially using the generateAsync() function.

**Comment by Stuk** [comment]
Now updated.
