### ISSUE TITLE
generateAsync doesn't work in window.beforeunload event.

### ISSUE THREAD

**Issue by bassist-hayato** [Stuk/jszip#686]
I want to create a zip file and upload it to the server when closing the browser.

but, running `generateAsync` after firing the `window.beforeunload` event does not produce a zip file.

The following is the code I wrote, but none of it works.
```
onBeforeUnload() {
    ...
    zip.generateAsync({type: 'base64'}).then(base64 => {
        // upload
    });
}
```
```
onBeforeUnload() {
    ...
    let base64 = await zip.generateAsync({type: 'base64'})
    // upload
}
```

**Comment by Stuk** [comment]
This is a limitation of what you can do in this event, not a bug in JSZip. 

See https://stackoverflow.com/questions/41909365/what-are-the-limitation-using-before-unload-event :

> You can put anything you want inside of a "beforeunload" callback, you're just not guaranteed it will execute unless you use synchronous/blocking code.

You could try using the synchronous API, however doing this work in beforeunload seems inadvisable to me.
