### ISSUE TITLE
unable to extract zip on mac and linux works fine on windows

### ISSUE THREAD

**Issue by anki7d** [Stuk/jszip#705]
`let z = new JSZip();
var files_info = [];
      var files = myDropzone.files

      files.forEach(file => {

        // z.file(file.name, file);
        z.file(file.name, file, { binary: true, compression: "DEFLATE" });
        // archive.file(file, { name: file.name });
        files_info.push({ 'name': file.name, 'size': file.size });

      });

z.generateAsync({
              type: "blob",
              compression: "DEFLATE",
              compressionOptions: { level: 9 }
            }).then(function (content) {
saveAs(content,'file.zip');

});`

**Comment by anki7d** [comment]
@Stuk  anything ?

**Comment by 4nkitd** [comment]
> @Stuk anything ?

found the issue while upload i was appending it to Formdata and then sending it to server, the content had some extra data then required.

**Comment by anki7d** [comment]
okay so in windows zip application ignored other form data content in side the file but in mac and linux it didn't thanks, my issue is resolved
