### ISSUE TITLE
The generateAsync function is paused when switching tab？

### ISSUE THREAD

**Issue by xwillmadeit** [Stuk/jszip#723]
Let's say i start a application in a chrome tab in which i call the generateAsync function with some files，then i switch to another tab，zip process seems to be paused，generateAsync({ type: 'blob' }).then will never get excuted only if i switch back to the tab，then the process continues to work. What happend？

**Comment by abkn9977** [comment]
> Let's say i start a application in a chrome tab in which i call the generateAsync function with some files，then i switch to another tab，zip process seems to be paused，generateAsync({ type: 'blob' }).then will never get excuted only if i switch back to the tab，then the process continues to work. What happend？

I am facing the same issue?
