### ISSUE TITLE
Why not just use Blob.arrayBuffer instead of transmitting by FileReader?

### ISSUE THREAD

**Issue by pillsilly** [Stuk/jszip#748]
https://github.com/Stuk/jszip/blob/112fcdb9953c6b9a2744afee451d73029f7cd2f8/lib/utils.js#L426-L446

Since the input is already Blob and desired output is array buff,
Any particular reason not to use Blob's interface [arrayBuffer()  ](https://developer.mozilla.org/zh-CN/docs/Web/API/Blob/arrayBuffer) ?

@dduponchel would you kindly provide some comments, thanks a lot.
I'm OK with providing the implementation.

**Comment by Stuk** [comment]
This is probably because `Blob.arrayBuffer` was not supported until Safari 14, and Internet Explorer still doesn't support it (although at this point we should probably deprecate support for IE!)

A patch to use `.arrayBuffer` if supported would be appreciated.
