### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by Androz2091** [Stuk/jszip#749]
Hello, I'm getting the following error when reading a big file (200mb) using jsip:

![Capture](https://user-images.githubusercontent.com/42497995/108719736-3e539380-7520-11eb-97dc-5ed485f33537.PNG)

Does someone know how to fix this issue? Thanks

**Comment by 101arrowz** [comment]
There's a string over 500MB (536870888 bytes, to be exact) large that's being generated. Are you doing `.async("string")` for a very large file? You can only use Uint8Array or streams to handle such massive files. (Side note, if you're looking for more performance in decompression, try [fflate](https://github.com/101arrowz/fflate)).

**Comment by Androz2091** [comment]
Yes, I was doing that. fflat can decompress these files?

**Comment by 101arrowz** [comment]
No program can store 500MB of data in a string. You'll need to use data streams to make this work. Specifically with JSZip, you need [`.internalStream('string')`](https://stuk.github.io/jszip/documentation/api_zipobject/internal_stream.html). You can do something similar with `fflate`'s ZIP streaming parser.

```js
import { Unzip, AsyncUnzipInflate, DecodeUTF8 } from 'fflate';
const uz = new Unzip();
uz.register(AsyncUnzipInflate);
uz.onfile = file => {
  // Same as the file you did .async("string") on
  if (file.name == 'YOUR_FILENAME') {
    const decoder = new DecodeUTF8();
    file.ondata = (err, data, final) => decoder.push(data, final);
    decoder.ondata = (str, final) => {
      // the variable "str" is the string data for the most recent chunk
    }
    file.start();
  }
}
// If you stream the input in, you can save memory. Alternatively, push() Uint8Array data in
uz.push(chunk1);
uz.push(chunk2);
...
uz.push(chunkLast, true);
```

**Comment by Androz2091** [comment]
All right thank you

**Comment by 101arrowz** [comment]
It depends on how you're loading the ZIP file. If it's from the network, try `Response.body.getReader()`. If from the filesystem, `File.stream().getReader()`.

If you're using an old browser or don't want to stream, just push the data as the final chunk. You need a `Uint8Array`. If you have a `Blob`:
```js
// blob is your blob data
uz.push(new Uint8Array(await blob.arrayBuffer()), true);
```

**Comment by Androz2091** [comment]
All right thank you, I'm going to try everything
