### ISSUE TITLE
docs: link in github "About" not up-to-date

### ISSUE THREAD

**Issue by peterpeterparker** [Stuk/jszip#758]
Hi Stuart,

Thank you for the great library 👍 

Just noticed that the link in the "About" section of the repo is not correct.

Is: `http://stuartk.com/jszip`

Should be: `https://stuk.github.io/jszip/`

Can't provide a PR to update this info 😉

<img width="1513" alt="Capture d’écran 2021-04-10 à 10 20 22" src="https://user-images.githubusercontent.com/16886711/114263542-69b61300-99e6-11eb-870a-3810dd2602b7.png">

**Comment by Stuk** [comment]
Thanks, fixed!
