### ISSUE TITLE
Empty Zip File

### ISSUE THREAD

**Issue by alisaleem252** [Stuk/jszip#798]
Empty Zip File if opened using winzip.
But content shows up if i use WinRaR.

Here is my piece of code.

Any help would be appreciated.

`
function saveToZip (filename, urls) {
const zip = new JSZip()
                    urls.forEach((url)=> {                  
                        const blobPromise = fetch(url).then(r => {
                            if (r.status === 200) return r.blob()
                            return Promise.reject(new Error(r.statusText))
                        })
                        var name = url.substring(url.lastIndexOf('/'));
                       
                       // folder.file(name, blobPromise);
                        zip.file(name, blobPromise, {base64: true, type: "application/zip"});
                    });

                    zip.generateAsync({type:"blob"})
                       .then(blob => saveAs(blob, filename))
                       .catch(e => console.log(e));
                } // function`

**Comment by adnanaslam475** [comment]
> Use generateAsync in a timeout

how can we use timeout?
