### ISSUE TITLE
 When I choose to unzip a file of more than 2G, an error is reported

### ISSUE THREAD

**Issue by mvpyb** [Stuk/jszip#799]
When I choose to unzip a file of more than 2G, an error is reported ：DOMException: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.

**Comment by gewentao** [comment]
same here, any updates？

**Comment by black0207** [comment]
what`s on

**Comment by aminfly** [comment]
any updates? same problem

**Comment by Stuk** [comment]
JSZip is not designed to handle files this large, sorry.

**Comment by FEliuyg** [comment]
So what is the recommended solution?
