### ISSUE TITLE
filter function does not work

### ISSUE THREAD

**Issue by WhaleYolo** [Stuk/jszip#810]
This is how I use it
```
const zip = new JSZip().folder(this.options.zipName);
for (let filename in compilation.assets) {
	const source = compilation.assets[filename].source();
	zip.file(filename, source);
}
zip.filter((relativePath, file) => {
	console.log(relativePath); 
	return relativePath === 'xxx'
})
```
filter returns true or false, but it doesn't actually do anything with the output

**Comment by Stuk** [comment]
`filter` returns a new array with only the items where the passed function returns `true`:

https://github.com/Stuk/jszip/blob/d4702a70834bd953d4c2d0bc155fad795076631a/lib/object.js#L201-L210

You can see usage here: https://github.com/Stuk/jszip/blob/master/test/asserts/filter.js
