### ISSUE TITLE
Built site error with Vite on 3.8.0 - Uncaught Error: Could not dynamically require "timers"...

### ISSUE THREAD

**Issue by erkage** [Stuk/jszip#815]
After updating to v3.8.0 when I build my app with Vite I've got this strange error when opening my built site in the browser:

`Uncaught Error: Could not dynamically require "timers". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.`

The same site with the same build process with v3.7.1 is totally fine.

Vite version is the latest 2.9.1 but that's not matter.

**Comment by Stuk** [comment]
Weird. There is [nothing in the new build](https://github.com/Stuk/jszip/pull/813/files#diff-8e14da262904c6d3590626f71bc671c9196f5a034624e14e47eb29495a544085) that should cause this error. Could it be because a transitive dependency updated at the same time?

**Comment by erkage** [comment]
There was no transitive dependency which is updated, in the lock file just the jszip's version changed.

BUT how it mysteriously came, it's now mysteriously gone. Nothing changed just updated again to 3.8.0 (as I did it before when made the ticket)... maybe I rebooted my machine in someday...

Thank you for checking and sorry for the false alarm.

PS.: no problem on 3.9.0 as well
