### ISSUE TITLE
3.9.0 :Build Error in index.d.ts(67,6)

### ISSUE THREAD

**Issue by cn-sunletian** [Stuk/jszip#816]
run build error:
 index.d.ts(67,6) error TS2456:Type alias 'InputFileFormat' circularly references itself.

**Comment by rashid-naico** [comment]
Build failed with this messge
![image](https://user-images.githubusercontent.com/85868168/161902591-f3b1e6d1-99e6-4bbc-813a-f69a64422544.png)
