### ISSUE TITLE
jszip.min.js:13 Uncaught (in promise) Error: nodebuffer is not supported by this platform

### ISSUE THREAD

**Issue by kuhnflyfish** [Stuk/jszip#821]
This error started after upgrading react-scripts to v5.0.1 which required 'buffer' as a dev dependency
<img width="554" alt="Screen Shot 2022-04-27 at 6 59 10 AM" src="https://user-images.githubusercontent.com/42548262/165523777-2afcd82a-e106-419f-a007-97cbae908cc2.png">

**Comment by Stuk** [comment]
Is this running in Node or in the Browser? Is this error occurring in your code or in react-scripts?

The test is for a Buffer global. If this is in your code in the browser you should use an output natively supported in the browser

https://github.com/Stuk/jszip/blob/f43810e361f20e764be85a8dee75944f3fbccb9e/lib/support.js#L7

**Comment by kuhnflyfish** [comment]
The error is being thrown in Chrome's console.  It is thrown on every page including most of them where jszip isn't even used.  So you are saying Chrome does not support typeof Buffer?  Another dev added shpjs to this project which has a dependency on jszip.  I'm unsure of anything they did related to jszip directly if anything.

**Comment by Stuk** [comment]
`Buffer` is a Node-only API, although some bundlers will polyfill it. As this is using `Buffer` in the browser I'm going to close this as I don't think it's a bug with JSZip. Let me know if I'm wrong.
