### ISSUE TITLE
The commits between tags v3.9.0 and v3.9.1 are different than the main branch

### ISSUE THREAD

**Issue by julienw** [Stuk/jszip#822]
Hi,
while updating to v3.9.1 I realized that the commits from the diff weren't part of the main branch -- or more exactly, that the commit hash don't match.

See: https://github.com/Stuk/jszip/compare/v3.9.0...v3.9.1
Open any commit => github shows them with the mention `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`.
We can also clearly see that the commit hashes are different than the ones on the main branch, for example:
https://github.com/Stuk/jszip/commit/396600779108447201fe81ffb25a4833bb0058a6 on the tag
vs
https://github.com/Stuk/jszip/commit/659599c02b9cf43eb4d82ef1f9a623d9062f46f0 on main

Also we can clearly see that github doesn't show the "v3.9.1" badge on the second one.

Is that expected? Have you rewritten the history of the main branch?

Thanks

**Comment by Stuk** [comment]
Thanks for noticing! I must have amended a commit after tagging locally. I have updated the 3.9.1 tag to point to the correct commit
