### ISSUE TITLE
cant zip files bigger than the ram size

### ISSUE THREAD

**Issue by uchihasharukh** [Stuk/jszip#832]
Hey how to zip large files.

Say i have 32gb ram and i want to zip 1tb size folder. The browser simply stores everything to ram and after its limit its throttling back to normal aborting the zip.

And also jszip cant zip big files in chrome says the following.

DOMException: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.

**Comment by Stuk** [comment]
I'm afraid JSZip isn't designed to handle files this large.

**Comment by coderGtm** [comment]
Any possible workarounds? Can we split the file into smaller-sized chunks and then pass it to the zip function and afterward combine them? Or is there a total zip file size limit above which JSZip doesn't go

**Comment by uchihasharukh** [comment]
hi if theres a way to store zipped chunk in temp file in devices local storage just like standalone 7zip we can achieve large zip
