### ISSUE TITLE
UTF-8 encoding for reading files

### ISSUE THREAD

**Issue by justekoro** [Stuk/jszip#837]
hi,
I'm trying to build a project using jszip.
but, when retreiving text content from the file, "é", "è", "à", "ç" etc becomes � (replacement character)

here is my code:
```
const axios = require('axios');
const jszip = require('jszip');
const zip = new jszip();
const url = "https://donnees.roulez-eco.fr/opendata/instantane";

const getData = async () => {
    const response = await axios({
        method: 'get',
        url,
        responseType: 'arraybuffer'
    });
    const data = await zip.loadAsync(response.data);
    const file = data.files["PrixCarburants_instantane.xml"];
    const text = await file.async("text");
    console.log(text);
};

getData();
```

**Comment by justekoro** [comment]
hi, bumping the issue

**Comment by nenge123** [comment]
new TextDecode().decode(await file.async("uint8array"));

**Comment by justekoro** [comment]
still not working

**Comment by justekoro** [comment]
update:
after getting the text as a buffer and converting it as a latin1 string, it works like a charm
`let text = await file.async("nodebuffer").toString("latin1");`
