### ISSUE TITLE
Uncaught RangeError: Array buffer allocation failed" when size exceeding 2 GB on Chrome

### ISSUE THREAD

**Issue by ankitwalia** [Stuk/jszip#838]
On chrome,

concat function

 case "uint8array":
            res = new Uint8Array(totalLength);

Uncaught RangeError: Array buffer allocation failed"

2145386496 bytes works fine

2145386496 + 1 fails - Uncaught RangeError: Array buffer allocation failed"

// create an ArrayBuffer with a size in bytes
const buffer = new ArrayBuffer(2145386496); // works fine
const buffer = new Uint8Array(2145386496); // works fine
console.log(buffer.byteLength);

const buffer = new ArrayBuffer(2145386497); // fails Uncaught RangeError: Array buffer allocation failed"
const buffer = new Uint8Array(2145386497); // fails Uncaught RangeError: Array buffer allocation failed"

**Comment by Stuk** [comment]
This is a limitation of Chrome, not of JSZip.
