### ISSUE TITLE
JSZIP: generateAsync does not work on headless chrome?

### ISSUE THREAD

**Issue by iiLearner** [Stuk/jszip#844]
Hi!

I'm using jszip to zip around 90 images and then upload this zip to amazon s3.
Currently, I need to do this operation with an automated process (using aws step functions + aws lambda), the lambda function launches chrome in headless mode and generates these images and adds them to zip, and that works correctly. However when the code comes to `zip.generateAsync` it never goes inside the callback and stays stuck there. Is there something I could do about that?

```js
console.warn("Finished recording...", zip);
          // generate the zip and return it
          zip.generateAsync({ type: "blob" }).then(function (content) {
            console.warn("Zip generated");
            resolve(content);
          });
```

```txt
<!--StartFragment-->

[0623/223846.218793:INFO:CONSOLE(19)] "Finished recording... [object Object]", source: https://xxx/app.min.js (19)
--
  | 2022-06-24T00:40:34.932+02:00 | 2022-06-23T22:40:34.931Z 8225f0d1-b231-479a-8c2e-423878b6be54 INFO Viewer did not respond to recording event within time limit, Closing the browser...

<!--EndFragment-->
```

the time limit ive tried so far is 180 seconds (3 mins)

jszip version: 3.10.0
puppeteer version: 10.1.0
chrome-aws-lambda version: 10.1.0

**Comment by Stuk** [comment]
The automated tests [run in Playwright](https://github.com/Stuk/jszip/blob/main/test/run.js#L28-L42), which is a version of a headless Chrome, so something similar definitely works. You may want to try adding an [onUpdate callback](https://github.com/Stuk/jszip/blob/main/test/run.js#L28-L42) to see if progress is being made.

**Comment by iiLearner** [comment]
> The automated tests [run in Playwright](https://github.com/Stuk/jszip/blob/main/test/run.js#L28-L42), which is a version of a headless Chrome, so something similar definitely works. You may want to try adding an [onUpdate callback](https://github.com/Stuk/jszip/blob/main/test/run.js#L28-L42) to see if progress is being made.

I will try to add the onUpdate callback now, but I probably forgot to mention this though; if I run headless chrome locally and do the test it works properly, however on lambda it doesnt. Is there anything else I can do to see whats going on or if an error is being generated? I do have the wrapping try/catch but it doesnt seem to catch anything

**Comment by iiLearner** [comment]
It seems like it does progress however the progress is very slow, it takes upto 5 mins to zip 10-15mb of files.

**Comment by nenge123** [comment]
how about try uint8array or arraybuffer


u8 = await generateAsync({type:"uint8array"});
file = new File(u8.buffer,"xxx.zip");
post = new Forumdata();
post.append("zip",file)

**Comment by iiLearner** [comment]
I will try doing so, thanks
