### ISSUE TITLE
corrupted zip: can't find end of central directory

### ISSUE THREAD

**Issue by nismojkee** [Stuk/jszip#853]
Hello
I met an error while trying exctract zip archive on brightsign using jszip.loadAsync

`
const fs = require("fs");
const JSZip = require("jszip");
let jszip = new JSZip();

function unzip(filePath) {
    fs.readFile(filePath, (err, data) => {
        if (err !== null) {
            console.error(`Meet an error on unzip: ${err}`);
        };
        console.log("Success read")
        jszip.loadAsync(data).then(
            function (zip) {
                console.log("Success");
                // do anything
            },
            function (unzipError) {
                console.log(`Meet an error on JSZip. ${unzipError}`);
            }
        )
    })
}

`

One time it work perfect, but next times i get in console
`
"Success read"
"Meet an error on JSZip. Corrupted zip: can't find end of central directory"
`

How do i can fix it?..

File that i want to unzip in attachments.

[widget_lukoil_sp_1.1_with_images.zip](https://github.com/Stuk/jszip/files/9198842/widget_lukoil_sp_1.1_with_images.zip)

**Comment by pjvds** [comment]
I can easily unzip this file with `UnZip 6.00 of 20 April 2009`

**Comment by nismojkee** [comment]
> I can easily unzip this file with `UnZip 6.00 of 20 April 2009`

Thank you a lot but the reason of this issue was in archivator, we're changed it and issue can be closed

**Comment by pjvds** [comment]
> Thank you a lot but the reason of this issue was in archivator, we're changed it and issue can be closed

Thanks for reporting this back. This is also a great hint for others that find this issue. 👍🏻
